### ISSUE TITLE
Colocar novo print (plataforma como está agora) no quadrado azul da plataforma não logada

### ISSUE THREAD

**Issue by helenalb** [hacklabr/paralapraca#100]

**Comment by brunosmartin** [comment]
O print da home não logado está com "Fulano de Tal", precisa tirar um print de um usuário com um nome q pareça real, e uma foto de uma pessoa (verificar direitos de imagem da foto).

@brunopaisano providencia o print, pede ajuda pra @helenalb se vc precisar pensar o nome a quetão dos direitos de imagem.
Depois de fazer o screenshot, anexa a imagem aqui e passa a issue para a @ariadnemelo

**Comment by brunopaisano** [comment]
Não preciso de ajuda, tá tudo certo. Usei uma imagem de um plugin do Sketch que serve pra colocar esses conteúdos "placeholders". O nome é o mesmo que eu tinha escolhido pros primeiros roughs que eu fiz. A tela demonstrativa tá no Zeplin: https://zpl.io/EQLT6

Aqui está o print: 
![entrada menu aberto_screenshot](https://cloud.githubusercontent.com/assets/20778816/17622974/0d82d4c0-6074-11e6-89f8-f2f2a564dcda.png)
