### ISSUE TITLE
Erro ao subir imagens no perfil

### ISSUE THREAD

**Issue by brunosmartin** [hacklabr/paralapraca#101]
Ao subir imagens grandes, dá erro.

**Comment by virgilio** [comment]
Eu testei essa issue localmente com imagens de até 10MB, incluindo um gif animado. Localmente e em ava.paralapraca.org.br

Tem mais algum detalhe como tamanho da imagem? 

Há possibilidade de essa issue estar relacionada com a #402?

**Comment by virgilio** [comment]
@brunosmartin e @laurybueno ^
