### ISSUE TITLE
ìcone do arquivos do topico e comentário aparece duplicado

### ISSUE THREAD

**Issue by brunosmartin** [hacklabr/paralapraca#106]

**Comment by brunosmartin** [comment]
a diretiva translate adiciona mais um elemento spam e fica com 2 pseudo elementos :before

**Comment by brunosmartin** [comment]
Só acontece quando tem mais de um arquivo anexo

**Comment by nicolavieira** [comment]
@brunosmartin tem como me passar o link de um post onde isso está acontecendo?

**Comment by nicolavieira** [comment]
@brunosmartin feito!
