### ISSUE TITLE
Criar mensagem de confirmação quando o usuário salva uma anotação na tela de curso

### ISSUE THREAD

**Issue by nicolavieira** [hacklabr/paralapraca#114]
atualmente o sistema não dá nenhum feedback quando a anotação é salva

o @brunosmartin disse que já está no cronograma de vocês mas pediu para mim criar uma tarefa

**Comment by brunopaisano** [comment]
@ariadnemelo , segue o link pra tela no Zeplin:

https://zpl.io/Z1vSKP

**Comment by nicolavieira** [comment]
@brunopaisano posso fazer essa mensagem aparecer por cima da caixa aberta? pois quando a pessoa salva a anotação a caixa permanece aberta - até porque ela pode querer continuar anotando alguma coisa

**Comment by brunopaisano** [comment]
https://zpl.io/Z1vSKP

Segue, @ariadnemelo !

**Comment by nicolavieira** [comment]
@brunopaisano vou fazer o layout da mensagem mas é bom pensar em como vai ser o comportamento dela: ela aparece e some depois de alguns segundos? some quando o usuário clica fora? acho que é algo a se ver com o @brunosmartin ou o @laurybueno também

**Comment by nicolavieira** [comment]
fiz num branch separado e vou esperar um feedback da #180 já que o mecanismo pra mensagem sumir em tese é o mesmo
