### ISSUE TITLE
Ajeitar as unidades - quando tem mais de sete fica torto

### ISSUE THREAD

**Issue by helenalb** [hacklabr/paralapraca#120]

**Comment by helenalb** [comment]
![captura de tela de 2016-08-16 14-50-34](https://cloud.githubusercontent.com/assets/20777077/17709898/5ddb263e-63c1-11e6-8215-a9fb17544d43.png)

**Comment by nicolavieira** [comment]
@brunosmartin criei duas classes, `.unit-1` pra quando o número de unidades for maior que 10, e `.unit-2` pra quando o número de unidades for maior que 20
