### ISSUE TITLE
Trocar "Projeto" por "Programa" na home e página interna e slug : http://ava.paralapraca.org.br/pages/o-projeto

### ISSUE THREAD

**Issue by helenalb** [hacklabr/paralapraca#137]

**Comment by nicolavieira** [comment]
@helenalb @brunosmartin preciso de um login de admin desse link pra fazer a alteração

**Comment by brunopaisano** [comment]
Fiz essa alteração em todas as telas do Zeplin tbm!

**Comment by laurybueno** [comment]
Dei permissões pra @ariadnemelo  no  django-admin da produção
