### ISSUE TITLE
Botão de postar resposta na atividade discussão tem ícone dobrado

### ISSUE THREAD

**Issue by laurybueno** [hacklabr/paralapraca#139]

**Comment by nicolavieira** [comment]
@laurybueno não consegui identificar onde está o problema, pode me passar um link de página com o exemplo?

**Comment by laurybueno** [comment]
@ariadnemelo eu escrevi esse título meio na pressa e não expliquei direito mesmo.

Mas já resolvi, então nem se preocupa com isso.
