### ISSUE TITLE
Aumentar comprimento da coluna tópico nas telas de fóruns

### ISSUE THREAD

**Issue by laurybueno** [hacklabr/paralapraca#142]

**Comment by nicolavieira** [comment]
@brunopaisano  @luisfbs  sabem me dizer quais são as novas orientações?

**Comment by brunopaisano** [comment]
@ariadnemelo segue as telas pra vc se orientar:
https://zpl.io/Z2dDhth
https://zpl.io/ZMvzG0
https://zpl.io/1cIrTH
