### ISSUE TITLE
Implementar o gostei nas atividades

### ISSUE THREAD

**Issue by laurybueno** [hacklabr/paralapraca#144]

**Comment by brunopaisano** [comment]
@laurybueno não vão precisar de tela pra essa issue?

**Comment by laurybueno** [comment]
@brunopaisano não devo precisar porque a tela dessa atividade é uma cópia da tela de tópico.

Por causa disso, acho que posso só usar o mesmo gostei do tópico de fórum.

Aqui um print pra ficar mais claro de que tela eu to falando:

![atividade-discussao](https://cloud.githubusercontent.com/assets/1108897/18015495/5d70aa7c-6b9e-11e6-847d-6619470b13a0.png)

**Comment by brunopaisano** [comment]
@laurybueno beleza!
