### ISSUE TITLE
Implementar novo layout para slides de unidades

### ISSUE THREAD

**Issue by laurybueno** [hacklabr/paralapraca#146]

**Comment by brunopaisano** [comment]
@ariadnemelo, agora é com vc! :D
https://zpl.io/Z2jzL13
https://zpl.io/ZV6lDM

**Comment by nicolavieira** [comment]
@brunopaisano essa tarefa refere-se apenas a mudança da tela mas essa ferramenta ainda não está implementada, então estou fechando

**Comment by laurybueno** [comment]
Duplicada da #155
