### ISSUE TITLE
Implementar layout dos slides de aula

### ISSUE THREAD

**Issue by nicolavieira** [hacklabr/paralapraca#155]
https://zpl.io/Z2jzL13
https://zpl.io/ZV6lDM

**Comment by laurybueno** [comment]
Vale acrescentar, @ariadnemelo, que dois templates de atividades consomem a diretiva do slide_panel
- timtec/activities/static/templates/activity_reading.html
- timtec/activities/static/templates/activity_image.html

Talvez, vc precise mexer nesses dois também para alcançar os resultados necessários.

**Comment by nicolavieira** [comment]
@laurybueno está pronto nos dois templates de atividades, as alterações de layout do tema estão no branch `slides-aula` no repositório paralapraca, já os templates das atividades estão no branch `paralapraca` no repositório do timtec
