### ISSUE TITLE
Em resoluções de tela muito altas, parte da caixa de seleção de tags fica obstruída

### ISSUE THREAD

**Issue by laurybueno** [hacklabr/paralapraca#156]
A propriedade "overflow: hidden" em "body.logged .site-wrapper" parece ser a responsável pelo problema. Mas sua remoção pode ter efeitos indesejados em outras áreas do site e esse reparo precisa ser melhor estudado. 

O problema também pode ser reproduzido quando se diminui o zoom do browser.

![overflow](https://cloud.githubusercontent.com/assets/1108897/18053614/c03f241e-6dd6-11e6-9eb5-7a9369b91322.png)

**Comment by nicolavieira** [comment]
@laurybueno 
só um comentário para explicar porque essa div existe com essas configuração: ela foi colocada para corrigir um bug em tablets, pois sem ela o usuário consegue "arrastar" o site para o lado e ver a parte que está escondida pelo overflow  (que é a parte que fica "para fora" quando o menu está aberto, por exemplo)

acho que uma solução seria fazer essa div ter a mesma altura que a altura do navegador, vou ver se consigo fazer isso apenas com css
