### ISSUE TITLE
Trocar label do menu lateral de "fórum" (singular) para "fóruns"(plural)

### ISSUE THREAD

**Issue by brunopaisano** [hacklabr/paralapraca#161]

**Comment by nicolavieira** [comment]
@laurybueno @brunosmartin o título "Fóruns" do dashboard não está dentro do esquema de tradução e pelo o que testei não tem tradução para a palavra em plural, como proceder nesse caso?

**Comment by laurybueno** [comment]
@ariadnemelo nós estamos eliminando do paralápraca o esquema de tradução atual. Ele vai ser substituído por uma outra abordagem mais tarde.

Pra esse caso, você pode eliminar a tag de tradução do menu e escrever "Fóruns" mesmo

**Comment by nicolavieira** [comment]
obrigada @laurybueno !
