### ISSUE TITLE
Diminuir fonte de títulos e subtítulos das páginas

### ISSUE THREAD

**Issue by nicolavieira** [hacklabr/paralapraca#162]

**Comment by nicolavieira** [comment]
@brunopaisano  fiz alguns ajustes, por favor quando puder dê uma olhada

**Comment by pimentaj** [comment]
Diminuir também o subtitulo em 2 pontos (anotações).  Nos fóruns especificos o tamanho esta ok, porém ainda precisamos aumentar distancia entre o botão(criar tóopico) e o titulo.

**Comment by nicolavieira** [comment]
opa, esse lande do botão tem outra tarefa, é a #164
