### ISSUE TITLE
Rever título nos fóruns específicos (passar para o padrão breadcrumb)

### ISSUE THREAD

**Issue by nicolavieira** [hacklabr/paralapraca#167]

**Comment by brunopaisano** [comment]
@ariadnemelo acho que pra essa não preciso fazer tela, é só replicar a lógica e o visual do "Fóruns > Avante e Entremeios" que está nessa tela de tópicos https://zpl.io/1l5bXW em toda tela de fórum específico (exs.: "Fóruns > Fórum Geral", "Fórum > Fórum Assessoras").

As telas de fóruns específicos são aquelas em que, no caso, são exibidos todos os tópicos relacionados a esse fórum.

**Comment by nicolavieira** [comment]
@brunopaisano isso é só em telas mobile, certo? (no caso, celulares mesmo?)

**Comment by brunopaisano** [comment]
@ariadnemelo pode ser para o desktop tbm! Acho que a navegabilidade fica melhor com o breadcrumb.

![captura de tela 2016-09-06 as 13 21 04](https://cloud.githubusercontent.com/assets/20778816/18281838/d1be372a-7434-11e6-940e-472d0479a59a.png)

A única mudança é que o botão "voltar para os tópicos" vira "voltar para os fóruns".

**Comment by nicolavieira** [comment]
@brunopaisano refiz todos os cabeçalhos e deixei esse dropdown por enquanto, depois se você quiser alterar para um layout definitivo só me dizer

![captura de tela de 2016-09-13 14 10 49](https://cloud.githubusercontent.com/assets/2034550/18483796/19e2d4fc-79bc-11e6-843f-0da9aa6f630f.png)
