### ISSUE TITLE
Reconfigurar menu amarelo (reformular os botões para melhor espaçamento e distribuição, considerando touchscreen)

### ISSUE THREAD

**Issue by nicolavieira** [hacklabr/paralapraca#169]
layout: https://app.zeplin.io/project.html#pid=576ad22a40ea7eb4350a160f&dashboard&tags=Responsivo

**Comment by brunopaisano** [comment]
@ariadnemelo, vc pode mandar um print de como está aí pra vc? Não percebi grandes mudanças no menu por aqui...

**Comment by brunopaisano** [comment]
@ariadnemelo, agora visualizei! Então, tem como aumentar um pouco a altura da select box de capítulo? Outra coisa, eu lembrei que não fiz um mecanismo de seleção de unidades! Já atualizo essa tela e te passo!

**Comment by brunopaisano** [comment]
![captura de tela 2016-09-05 as 11 53 36](https://cloud.githubusercontent.com/assets/20778816/18251457/a5f08074-735f-11e6-9792-6f796495fe96.png)

Um ajuste: essa parte amarela que ficou embaixo dos cinco botões pode ser tirada. Quando eu clico nela, abre a select box de unidades. No entanto, depois de tirar, esse espaço entre os cinco botões e a select box que a parte amarela causa pode ser preservado, deixando aparecer o fundo do site.

**Comment by brunopaisano** [comment]
@ariadnemelo, só lembrando que ainda falta aumentar um pouco a altura dos select boxes "capitulos" e "unidades", pra aumentar a área clicável. Acho que tá pequena pra touchscreen do jeito que tá implementado.
