### ISSUE TITLE
Atividade discussão deve ter um botão que manda para a próxima unidade

### ISSUE THREAD

**Issue by laurybueno** [hacklabr/paralapraca#176]

**Comment by laurybueno** [comment]
@brunopaisano quando você tiver um tempo então, propõe um desenho bacana para o botão de próxima unidade. Tá desse jeito agora:

![btn-proxima-unidade](https://cloud.githubusercontent.com/assets/1108897/18142121/8f4e50b0-6f92-11e6-8529-69cf21a2c6bb.png)

@ariadnemelo para colocar esse botão, eu preferi deixar os estilos inline para não mexer nos arquivos css e bagunçar as coisas. Quando o Paisano tiver o layout certo, você pode implementar nesse aquivo do repositório timtec: activities/static/templates/activity_discussion.html

**Comment by brunopaisano** [comment]
Segue as tela ilustrando o botão:
https://zpl.io/Z2fR4QM
https://zpl.io/Zx9YAr
https://zpl.io/cbAEg
