### ISSUE TITLE
Tirar sublinhado dos ícones dos botões de reação (gostei, comentar, responder)

### ISSUE THREAD

**Issue by brunopaisano** [hacklabr/paralapraca#178]

**Comment by pimentaj** [comment]
![screenshot from 2016-09-02 15-27-43](https://cloud.githubusercontent.com/assets/18036352/18214152/d567ec10-7121-11e6-9a16-2481971317d4.png)

**Comment by brunopaisano** [comment]
@pimentaj Seria pra tirar o sublinhado do coração e da seta e deixar só das palavras. Tem como? Não sei se é vc ou a @ariadnemelo que fariam isso hehe! Lembro que a @ariadnemelo disse que dá pra fazer, mas daria um certo trabalho... Não é prioridade de qq forma!
