### ISSUE TITLE
Ajustes nos títulos na tela de tópico

### ISSUE THREAD

**Issue by brunopaisano** [hacklabr/paralapraca#179]
- [x] Aumentar espaçamento entre linhas no título
- [x] Deixar a palavra "por" e o nome do usuário com mesmo tamanho de fonte (o nome está bem menor que o "por)
- [ ] Rever bug na primeira linha do título (está cortando)
- [x] Diminuir tamanho de fonte do título do tópico

**Comment by nicolavieira** [comment]
@brunopaisano acho que fiz todas tirando o terceiro item que não consegui reproduzir o bug aqui (ou talvez eu esteja olhando a coisa errada)? você pode me enviar um print?

**Comment by brunopaisano** [comment]
@ariadnemelo tbm não to mais conseguindo localizar o bug... acho que com a diminuição da fonte do título já foi resolvido!

**Comment by nicolavieira** [comment]
@brunopaisano beleza, estou fechando mas qualquer coisa reabrimos
