### ISSUE TITLE
Alterações na tela do fórum

### ISSUE THREAD

**Issue by nicolavieira** [hacklabr/paralapraca#18]
https://app.zeplin.io/project.html#pid=576ad22a40ea7eb4350a160f&sid=577d8bb7b97c2fb37a9a25b7
- [ ] "limpar filtro" e "filtrar por tags e categorias" no header

**Comment by ariadnemelo** [comment]
@brunopaisano @luisfbs se houver mais alterações nessa tela podem comentar aqui por favor?

**Comment by brunopaisano** [comment]
Pode deixar, @ariadnemelo ! 😄

**Comment by nicolavieira** [comment]
fechando essa issue pois não faz mais sentido, é preciso abrir outras mais específicas para finalizar o header da página de fórum
