### ISSUE TITLE
Fazer instalação do Rocket Chat para entremeios

### ISSUE THREAD

**Issue by brunosmartin** [hacklabr/paralapraca#181]
deve ficar em chat.ava.paralapraca.org.br

**Comment by brunosmartin** [comment]
Creio que este seja o melhor método: https://rocket.chat/docs/administrator-guides/authentication/iframe/

**Comment by fabiomontefuscolo** [comment]
ver como embedar o rocket.chat inteiro em um iframe
ver como embedar uma sala do rocket.chat em um iframe
enviar email pedindo o dominio `chat.paralapraca.org.br` (amanhã)
