### ISSUE TITLE
Colocar títulos das unidades

### ISSUE THREAD

**Issue by helenalb** [hacklabr/paralapraca#189]

**Comment by brunopaisano** [comment]
@laurybueno Pelo que eu entendi, essa issue se refere ao títulos mouse-over que aparecem nas bolinhas da linha do tempo das unidades, que a @helenalb ficou de fazer. Mas tenho uma dúvida: aqui tbm tá incluso os títulos que não são do mouse-over, ou seja, os que a gente combinou de colocar logo abaixo no menu amarelo?

Tudo isso para saber: vou precisar fazer tela pra isso? rs

**Comment by laurybueno** [comment]
@brunopaisano Esta isseu é justamente para os títulos entre a linha do tempo e os slides das unidades. A questão do mouse-over foi resolvida em uma issue já encerrada.

É uma boa fazer tela pra isso sim. Por enquanto, tá implementado daquele jeito gambis que eu conversei com vc em cinco minutos há uns dias. A saber: 

![titulo](https://cloud.githubusercontent.com/assets/1108897/18359450/5e403c7e-75d0-11e6-86b8-6a6596f77143.png)

**Comment by brunopaisano** [comment]
Já temos tela para isso! 
https://zpl.io/ZLFezt

Tá aqui, @ariadnemelo !
