### ISSUE TITLE
Descobrir o mistério das bolas quadradas e resolver

### ISSUE THREAD

**Issue by helenalb** [hacklabr/paralapraca#190]
Em outros computadores, as bordas quadradas durante mouseover ficam bem mais pronunciadas do que o que podemos ver a seguir:

![screenshot from 2016-09-05 11 03 26](https://cloud.githubusercontent.com/assets/1108897/18250179/b48bdd56-7358-11e6-96d6-2879778ce285.png)

**Comment by pimentaj** [comment]
Creio que pode por causa do border-radius, pois esta 100% e isso altera, se colocarmos em px pode acontecer de não existir mais os quadrados.

**Comment by pimentaj** [comment]
file:///home/jullia/Pictures/bolasquadradas.png

**Comment by pimentaj** [comment]
![bolasquadradas](https://cloud.githubusercontent.com/assets/18036352/18213759/32b8baa4-7120-11e6-845e-aad751cb4ff2.png)

**Comment by nicolavieira** [comment]
o problema era o `span` que o angular adiciona dentro do elemento com a classe `unit` que também precisa ter o border-radius, imagino que agora tenha resolvido mas qualquer coisa por favor me avisem
