### ISSUE TITLE
Corrigir menu superior na página incial, sem login

### ISSUE THREAD

**Issue by pimentaj** [hacklabr/paralapraca#200]

**Comment by pimentaj** [comment]
![screenshot from 2016-09-02 15-58-16](https://cloud.githubusercontent.com/assets/18036352/18215217/844f58f4-7126-11e6-89db-fdefd461779d.png)

**Comment by nicolavieira** [comment]
- [x] menu hamburguer no canto superior direito
- [x] label MENU

**Comment by nicolavieira** [comment]
@brunopaisano é uma sugestão, sinta-se a vontade para modificar
![menu-aberto](https://cloud.githubusercontent.com/assets/2034550/18251658/adfe06b4-7360-11e6-81aa-a24612f055f6.png)
![menu-fechado](https://cloud.githubusercontent.com/assets/2034550/18251659/ae182bf2-7360-11e6-9edd-b413f2d3fff6.png)

**Comment by nicolavieira** [comment]
@brunosmartin as alterações estão no branch `menu-responsivo` pois não consegui deixar o menu funcional, o angular tá dando erro nessa página

**Comment by laurybueno** [comment]
@ariadnemelo a mudança para o base principal parece ter resolvido os problemas de injeção de dependências. Você deve conseguir continuar trabalhando no menu agora. Avise se precisar de alguma coisa.
