### ISSUE TITLE
revisar e corrigir o responsivo

### ISSUE THREAD

**Issue by brunosmartin** [hacklabr/paralapraca#23]

**Comment by nicolavieira** [comment]
eu já andei fazendo isso então pode ser mais específico?

**Comment by brunosmartin** [comment]
A ideia é sempre que tiver sem outras tarefas vir pra esta e ir fazendo uma
revisão geral, e  gerar outras issues
Dei uma testada ontem e tem bastante coisa por fazer.

Em 2 de ago de 2016 10:40, "Ariadne Melo" notifications@github.com
escreveu:

**Comment by nicolavieira** [comment]
Será que você consegue listar então quais foram as coisas que você viu por fazer? Se ficar só na minha mão revisar tudo e listar as coisas fica complicado porque muita coisa vai passar batido.

**Comment by nicolavieira** [comment]
duplicada da #149
