### ISSUE TITLE
Área de notificações muda seta de lugar após ser carregada

### ISSUE THREAD

**Issue by laurybueno** [hacklabr/paralapraca#236]
![seta_notificacoes](https://cloud.githubusercontent.com/assets/1108897/18760665/6532798a-80d8-11e6-85a3-d382bdb601df.gif)

**Comment by nicolavieira** [comment]
@laurybueno não consigo reproduzir o bug pois as notificações não carregam no meu ambiente, será que tem como resolver isso?

**Comment by laurybueno** [comment]
@ariadnemelo claro! me dá um tmate quando vc tiver um tempo
