### ISSUE TITLE
Botão de criar nova mensagem não está funcionando

### ISSUE THREAD

**Issue by nicolavieira** [hacklabr/paralapraca#264]
Não consegui identificar o problema. O template é o `messages.html`

**Comment by laurybueno** [comment]
Problemas do Angular estão corrigidos. No entanto, ainda são necessárias mudanças no backend para que as mensagens possam ser criadas corretamente.

![screenshot_2016-10-21_11-09-49](https://cloud.githubusercontent.com/assets/1108897/19599316/07c2a1a4-977f-11e6-9ff6-05b63172ae32.png)
