### ISSUE TITLE
Terminar de corrigir layout da página de edição de módulo

### ISSUE THREAD

**Issue by nicolavieira** [hacklabr/paralapraca#27]
Faltou a área de aulas no fim da página

**Comment by nicolavieira** [comment]
@brunosmartin falta o número das unidades na parte de edição das aulas

**Comment by brunopaisano** [comment]
- [x] Opção para definir status do capítulo (público ou rascunho)
- [x] Solução para definir capítulo quanto a seu papel na avaliação (se contam ou não)

**Comment by nicolavieira** [comment]
duplicada na #222
