### ISSUE TITLE
Testar o AVA em iPad e Nexus

### ISSUE THREAD

**Issue by brunopaisano** [hacklabr/paralapraca#270]
IMPORTANTE:
Testar na horizontal e na vertical

Atentar para:
- Tamanhos de fontes
- Espaçamentos
- Dimensões de assets, boxes, barras e menus
- UX de desktop que não valham a pena para responsivo
- Eventuais melhoras na UX do responsivo (de preferência, não muito complexas de implementar)

**Comment by brunopaisano** [comment]
- Módulos
- [ ] Botões superiores
- [ ] Bolinhas de unidades
- [ ] Select box de capítulos
- [ ] Anotações fazendo o módulo (anotar, salvar, mensagem feedback)
- [ ] Tela de anotações do módulo
- [ ] Fazer atividades (tipos diversos, se possível)
- [ ] Editar e apagar atividades
- [ ] Edição do módulo - mudar título, mudar URL, inserir atividade, editar texto do box azul, funcionalidades box verde, capítulos (bolinhas de unidade, remover, ordenar), descrição de capítulo
- [ ] Edição de capítulo - apagar capítulo, switch "público/rascunho", salvar alterações (mensagem feedback), editar título do cap, select box "editar outro capítulo", switch avaliação, bolinhas de unidade, adicionar unidade, nome unidade, apagar unidade, inserir vídeo, inserir imagem, descrição unidade.

**Comment by brunopaisano** [comment]
- Fóruns
- [ ] Links dos itens "ultimas postagens"
- [ ] Marcação de tópico não lido
- [ ] Filtragem por tags e categorias
- [ ] Busca (se houver)
- [ ] Criação de novo tópico
- [ ] Edição de tópicos, respostas e comentários
- [ ] Apagar tópico/comentário/resposta
- [ ] Passar páginas em fóruns específicos
- [ ] Navegabilidade entre as telas (Fóruns > Fórum X > Tópico Y e vice-versa)
- [ ] Anexar arquivos em tópico/comentário/resposta
- [ ] Botão "gostei"
- [ ] Select box de fóruns

**Comment by brunopaisano** [comment]
- Anotações
- [ ] Botões "página inicial" e "continuar módulo"
- [ ] "Ver todas" e "ocultar"
- [ ] Botões "descartar" e "editar" nas anotações específicas

**Comment by brunopaisano** [comment]
- Perfil
- [ ] Editar perfil
- [ ] Links externos
- [ ] Ver certificados

**Comment by brunopaisano** [comment]
- Pré-login
- [ ] Fazer login (correto e incorreto)
- [ ] Fazer cadastro
- [ ] Links para textos institucionais
- [ ] Testar menu hamburguinho (se tiver)
- [ ] Avaliar a disposição dos bichos
- [ ] Acesso Avante e Inst. C&A
- [ ] FAQ - expandir e retrair perguntas

**Comment by nicolavieira** [comment]
relacionada a essa tarefa tem a #221

**Comment by brunopaisano** [comment]
Boa, @ariadnemelo !
