### ISSUE TITLE
Tela de usuários e grupos: retornar os grupos do usuário na coluna de grupos da aba usuários

### ISSUE THREAD

**Issue by nicolavieira** [hacklabr/paralapraca#279]
atualmente essa funcionalidade não existe, o texto está hardcoded no template apenas de exemplo

![grupos](https://cloud.githubusercontent.com/assets/2034550/19812052/c2acb5e8-9d12-11e6-8bd5-90278f7f9da0.png)

está no branch `usuarios-grupos`, template `users.html`

**Comment by laurybueno** [comment]
Ícone de menu no canto esquerdo superior parece estar deslocado no branch `usuarios-grupos`.

Não sei dizer se ele estava assim no estado original do branch, ou se só ficou assim depois de receber o merge do `master`. De qualquer forma, seria bom se você conseguisse dar uma olhada, @ariadnemelo :)

![screenshot from 2016-11-29 11-47-40](https://cloud.githubusercontent.com/assets/1108897/20712126/fe5c0fb4-b629-11e6-8815-c6cba0f6659e.png)

**Comment by laurybueno** [comment]
@ariadnemelo você consegue dar mais um tapa nessa página? Ela fica em `/admin/users`

Para tudo funcionar, você precisa estar no branch `usuarios-grupos` do paralapraca e no branch `paralapraca-usergroups` do timtec.

Como esse branch ainda não recebeu os certificados, ele deve ser incompatível com o banco de dados local que vc tem agora. Será preciso deletá-lo e recriá-lo a partir do arquivo que eu te dei há alguns dias. Avise se precisar de ajuda nesse processo.

Na aba de usuários, precisam de atenção:


- [x] caixa de busca, porque eu coloquei para dentro da aba
- [x] tamanho das colunas pode se beneficiar de uma revisão. Talvez dar mais espaço pra nomes e menos para grupos. Quando o email da pessoa é grande, a coluna quebra e truncar os emails não é um bom caminho
- [x] a paginação no final da página está recebendo os estilos do fórum. Você pode dar um estilo próprio pra ela que combine melhor com a página?

Na aba de grupos:
- [x] o botão de novo grupo está com position: absolute (graças a mim). Você pode usar CSS de adultos pra posicionar ele, por favor?
