### ISSUE TITLE
Inserir opções de "Administração" no menu lateral

### ISSUE THREAD

**Issue by brunopaisano** [hacklabr/paralapraca#282]
Serão as opções de administração de "Usuários e grupos" e de "Módulos" (https://zpl.io/ZWM260 | https://zpl.io/16oTHA | https://zpl.io/Z18cdvn | https://zpl.io/2atPNv).

**Comment by nicolavieira** [comment]
deixei o link pra tela de "usuários e grupos" comentado já que essa tela ainda não está pronta (faltam implementar algumas funcionalidades)
