### ISSUE TITLE
Corrigir layout da página de opções do certificado e do comprovante

### ISSUE THREAD

**Issue by nicolavieira** [hacklabr/paralapraca#30]

**Comment by nicolavieira** [comment]
dei um tapa mas essa tela não tem layout @brunopaisano

**Comment by nicolavieira** [comment]
certificado

![captura de tela 2016-11-07 as 14 46 49](https://cloud.githubusercontent.com/assets/2034550/20102403/27754eac-a5ad-11e6-86b4-89a994271868.png)

comprovante

![captura de tela 2016-11-07 as 13 50 22](https://cloud.githubusercontent.com/assets/2034550/20103234/4ea921bc-a5b0-11e6-9034-0456ea101beb.png)

**Comment by brunopaisano** [comment]
Só pra avisar, eu tive que mudar a fonte do certificado porque essa que eu usei não tinha no Google Fonts. Substituí por outra parecida.
