### ISSUE TITLE
Corrigir (ou retirar) o link para anotações do curso

### ISSUE THREAD

**Issue by helenalb** [hacklabr/paralapraca#34]
![captura de tela de 2016-08-02 15-31-03](https://cloud.githubusercontent.com/assets/20777077/17340306/fef311b4-58c5-11e6-8e1b-0569852459f3.png)

O link não leva pra lugar nenhum

**Comment by nicolavieira** [comment]
@brunosmartin pode ajudar nessa? não consegui corrigir, o link do jeito que está imprime o número e não o nome da aula, por isso está quebrado

**Comment by brunopaisano** [comment]
@ariadnemelo , já resolvemos essa issue?
