### ISSUE TITLE
[Relatórios] Serializer e View para módulos com filtros por turmas

### ISSUE THREAD

**Issue by laurybueno** [hacklabr/paralapraca#346]
Campos esperados:

- Nome
- CPF
- Email
- Porcentagem realizada por capítulo
- Atividades (feitas ou não)
- Concluintes (Certificados)
- Número de comentários nas atividades (em todas, não precisa separar)*
- Número de gostei nas atividades (em todas, não precisa separar)*
- data e hora do último login

Testes automatizados também são esperados com essa entrega. O padrão desejável pode ser encontrado [aqui](https://github.com/hacklabr/django-discussion/tree/master/tests).

**Comment by tiagofassoni** [comment]
atividades == activities
capitulos == lessons

**Comment by laurybueno** [comment]
Fechado pelo pull request #351
