### ISSUE TITLE
[Relatórios] Serializer e view para o relatório geral da plataforma com filtro opcional por grupos

### ISSUE THREAD

**Issue by laurybueno** [hacklabr/paralapraca#347]
Colunas:

- Nome
- CPF
- Email
- Último acesso
- Data de criação do usuário na plataforma
- Uma coluna para cada módulo em que ele está matriculado com a porcentagem cumprida no dado módulo
- Coluna de turma do usuário para cada módulo
- Possui ou não certificado (termo preferido pela Avante é “concluinte”)
- Tópicos criados 
- Comentários feitos
- “Gostei” dados

Testes automatizados também são esperados com essa entrega. O padrão desejável pode ser encontrado [aqui](https://github.com/hacklabr/django-discussion/tree/master/tests).

**Comment by tiagofassoni** [comment]
módulo == curso

**Comment by laurybueno** [comment]
Fechado pelo pull request #351
