### ISSUE TITLE
[Relatórios] Serializer e view para relatório geral com sumarizações

### ISSUE THREAD

**Issue by laurybueno** [hacklabr/paralapraca#348]
Colunas:

- Total de usuários
- Usuários por turma
- Usuários por curso
- Total de concluintes por curso
- Tópicos criados*
- Comentários feitos*
- “Gostei” dados*

Testes automatizados também são esperados com essa entrega. O padrão desejável pode ser encontrado [aqui](https://github.com/hacklabr/django-discussion/tree/master/tests).

**Comment by tiagofassoni** [comment]
Os tópicos, comentários e "gostei" são agregados pelo nível geralzão do fórum. 

O total de concluintes é para ser pego separando pelo tipo de certificado (a fazer com um dict comprehension)

**Comment by laurybueno** [comment]
Fechado pelo pull request #351
