### ISSUE TITLE
Há 6 CourseStudents sem class

### ISSUE THREAD

**Issue by tiagofassoni** [hacklabr/paralapraca#349]
O código usado para encontrar os CourseStudents sem class foi este:

```python
listao = []

for x in CourseStudent.objects.all():
    try:
        x.get_current_class()
    except:
        listao.append(x)
```
Todos os CourseStudents sem class ocorrem no módulo de gestão. O caso mais "preocupante" é o Admin EAD

**Comment by tiagofassoni** [comment]
Os 6 usuários, ao menos na base de dev, são:

[<CourseStudent: Módulo de Gestão - Edil****>,
 <CourseStudent: Módulo de Gestão - Sim****>,
 <CourseStudent: Módulo de Gestão - Thay***,
 <CourseStudent: Módulo de Gestão - Nil***  - CAM>,
 <CourseStudent: Módulo de Gestão - hel***+gestores@h*******>,
 <CourseStudent: Módulo de Gestão - admin EAD>]

**Comment by tiagofassoni** [comment]
São 47 coursestudents nesse módulo de gestão no total.

**Comment by laurybueno** [comment]
Problema resolvido em produção com ajuda de 52332c719cf3bf222ab689510944f48d46c196dd
