### ISSUE TITLE
Tirar os Links da Página do Material didático do Modulo introdutório(não se se eles precisam estar aí)

### ISSUE THREAD

**Issue by helenalb** [hacklabr/paralapraca#35]
![captura de tela de 2016-08-02 14-32-03](https://cloud.githubusercontent.com/assets/20777077/17338455/d9758866-58bd-11e6-944c-e48ecc5d8c4a.png)

**Comment by brunosmartin** [comment]
Presisamos resolver isso de forma mais global. Fechando esta por hora
