### ISSUE TITLE
Implementação básica de frontend para django-cards

### ISSUE THREAD

**Issue by laurybueno** [hacklabr/paralapraca#353]
# Página de listagem de cards
- [x] paginação dos cards -- aceito sugestões;
- [x] @ariadnemelo precisa fazer algo similar a `.praticas-certificadas` e `.praticas-independentes`, mas aplicado aos cards, não às linhas, de forma a poder ter cards com status diferente na mesma linha;
- [x] não sei se o scroll warning deveria ter um comportamento específico.
- [ ] implementar CSS
- [x] pluralização das curtidas

# Página de visualização de detalhes
- [x] implementar botão Curtir/Descurtir;
- [x] clicar em uma tag deveria abrir a lista de cards com aquela tag?
- [ ] implementar CSS
- [x] pluralização das curtidas

# Página de criação, edição e deleção de cards
- [ ] HTML
- [ ] CSS
- [x] lógica de frontend (angular)

**Comment by nicolavieira** [comment]
# **Página de listagem de cards**

- [ ] @ariadnemelo precisa fazer algo similar a .praticas-certificadas e .praticas-independentes, mas aplicado aos cards, não às linhas, de forma a poder ter cards com status diferente na mesma linha; **(ainda precisam da minha ajuda?)**
- [ ] implementar CSS **(está implementado no branch `cards`)**

# **Página de visualização de detalhes**

- [ ] implementar CSS **(em endamento)**

**Comment by leopiccionia** [comment]
Por motivos de organização, vou desmembrar a tarefa "Página de criação, edição e deleção de cards".
- [X] Criação de card
    - [x] Galeria de imagens
    - [x] YouTube *embeds*
- [x] Edição de cards
    - [x] Cancelar alteração do último campo
- [x] Validações, etc.
- [X] Deleção de cards
- [x] Navegação
- [x] Carrossel
