### ISSUE TITLE
Revisão de demandas do cliente para o Assim se Faz

### ISSUE THREAD

**Issue by laurybueno** [hacklabr/paralapraca#354]
# Demandas de design do Assim se Faz
- [x] propor cores do EAD.Entremeios
- [x] Precisamos mandar um briefing sobre como devem ser as imagens padrão de cada eixo e como deve ser a imagem padrão temporária
- [x] Resolver o bug que impede galerias de aparecerem na produção
- [x] cards na home devem ter limite de altura
- [x] Telas de cards precisam de um fundo análogo aos fundos de outras telas (análogo ao fundo fórum)
- [x] Na página individual de cards: Alinhamento incorreto do “0 gostou” 
- [x] Na página individual de cards: Botão “voltar” está péssimo
- [x] Na página individual de cards: Verde nos botões superiores não faz parte da identidade visual da plataforma
- [x] Contador de práticas não deve ter o mesmo estilo visual do título na navegação horizontal de cards na home
- [x] Título de seções na lista de cards precisam ser maiores. Colocar um fundo em cada linha de práticas (validadas e não) pode ser uma opção para melhorar o destaque
- [x] listagem geral de cards na home (na parte de baixo) nem sempre mostra três cards por linha (há uma linha com apenas um card)
- [x] Tela de edição de card: Ícone no botão de lixeira na edição de galeria deve ser branco
- [x] Tela de edição de card: Rever a galeria de edição (lixeira colada, um retângulo a mais dentro da edição, números colados uns aos outros)
- [x] Tela de edição de card: Campo de tags deve ter  seu estilo ajustado
- [x] Os cards parecem estar muito grudados
- [x] título do card na home não corresponde ao estilo do invision
- [x] na home de cards, o texto do eixo tb ainda não corresponde ao estilo do invision
- [x] Na página individual de cards: estilo da contagem de likes não corresponde ao estilo do invision
- [x] Na página individual de cards: Falta espaço entre a galeria e o bloco de dicas
- [x] Na página individual de cards: Padding do conteúdo está muito menor do que no layout.
- [x] Na página individual de cards: padding do box dicas tá errado
- [x] Na página de busca: segunda linha de filtros fica colada com a primeira quando há mais de uma linha de elementos ativados (além disso, a primeira linha está colada nos campos de texto)

# Demandas de lógica frontend
- [x] títulos devem ter limite de caracteres
- [x] “Publicado por” deve ser em minúsculas e sem “dois pontos”
- [x] Ordem dos cards na home: mais recentes primeiro
- [x] Subir o “<3 0” para a mesma linha do “Publicado por”. A palavra “gostou” deve ser removida
- [x] Mudar “Gostar” por “gostei” (seguir tela do invision)  na individual de card (https://projects.invisionapp.com/d/main#/console/7788828/233753305/preview)
- [x] botão de voltar deve aparecer para todos os usuários e não só para admins
- [x] na tela de edição de cards: a pessoa deve ser alertada se tentar sair da página sem salvas
- [x] Sobre a paginação horizontal de cards na home: todos os cards devem ser acessíveis por ela. Vamos rediscutir quando tivermos mais melhorias visuais
- [x] Na página individual de cards: slides não devem ter auto-play
- [x] Na página individual de cards: Na área de tags, botão do público deve ser clicável
- [x] Na página individual de cards: breadcrumbs devem ser clicáveis desde o Assim se Faz
- [x] Na página individual de cards: Tags não devem aparecer na parte de cima
- [x] Na página individual de cards: “Chamada para a proposta” deve ser apagado
- [x] Tela de edição de card: Deve haver um limite de 5 slides (sejam eles fotos ou vídeos)
- [x] Tela de edição de card: Imagens devem pedir uma confirmação antes de serem excluídas. Assim como exclusão de prática
- [x] Tela de edição de card: Primeira imagem deve ser a de capa (imagem escolhida para exibição na home de cards)
- [x] Tela de edição de card: Novas imagens devem ir para o final do carrossel e não para o começo
- [x] Tela de edição de card: Deve ter um botão de salvar no fim da página tb
- [x] Adms não estão conseguindo editar as práticas não certificadas que não são deles mesmos
- [x] Devemos colocar o campo de select do angular ui na busca de cards
- [x] TinyMCE limitar a edição a: negrito, itálico, listas ordenadas e não ordenadas e links. Fora isso, formatações loucas de word devem ser limadas
- [x] Na página individual de cards: botão voltar precisa lembrar da sua busca (se houve uma)
- [x] Tags devem ser Case Insensitive (Corpo e corpo devem ser a mesma tag)
- [x] dados (foto e nome) de perfil de usuário não aparecer no canto esquerdo superior do ava enquanto estamos nas telas de cards
- [x] quando uma nova tag grande demais é inserida, a inserção deve ser impedida e não ter a palavra cortada no limite de careacteres (está sendo cortada em 12) (a mesma coisa acontece qdo vemos tags na produção que já são grandes demais)
- [ ] Tela de edição de card: Bug esporádico: quando eu clico numa área de texto, o box do tinymce pode aparecer com uma altura gigantesca até ser clicado pela primeira vez
- [x] título do card não deve aparecer nos breadcrumbs
- [x] Cada eixo deve ter sua própria imagem padrão (não será para a entrega desta terça 26/09)
- [x] confirmação para deletar card não está funcionando em produção
- [x] escrever uma tag que não existe na busca não deve me permitir selecionar uma outra tag não relacionada. A seleção tem que ficar vazia. Além disso, deve ficar claro qual tag está sendo selecionada
- [x] bug a ser investigado: depois de deletar um card, a mari foi levada para a home e esta ficou vazia e sem animação de loading enquanto os cards carregavam
- [x] imagem na lista de cards deve ser clicável
- [x] textos das tags não deve sumir logo depois de apertar o botão salvar

# Demandas possivelmente híbridas
- [x] na home: tags devem ser limitadas pelo espaço disponível e ter um “+” que quando clicado leva para a página de detalhes de cards
- [x] Cards só podem aparecer com no máximo duas linhas na home. Qdo ele tiver uma linha só, ele deve deixar espaço em branco mesmo
- [ ] Tela de edição de card: Mari está descontente com a lógica de salvar campos individualmente para só depois salvar tudo. Precisamos rediscutir com o Bruno

**Comment by tiagofassoni** [comment]
Para a ```Tags devem ser Case Insensitive (Corpo e corpo devem ser a mesma tag)```, coloquei um ```TAGGIT_CASE_INSENSITIVE = True``` no settings do repo.

**Comment by leopiccionia** [comment]
Em relação ao item `na home: tags devem ser limitadas pelo espaço disponível e ter um “+” que quando clicado leva para a página de detalhes de cards`, a solução atual é limitar heuristicamente a exibição a duas tags, truncadas *a priori* (durante a criação de tags) em 12 caracteres cada.

Se alguém tiver uma solução superior, estou aberto a soluções.

**Comment by nicolavieira** [comment]
quanto a questão 

> Na página individual de cards: padding do box dicas tá errado

o invision mostra 20px e é o que está sendo atualmente

**Comment by nicolavieira** [comment]
@laurybueno Peço por gentileza que novas demandas que precisem da minha ajuda sejam feitas em novos comentários nessa tarefa e não inseridas na lista acima, pois novos itens inseridos no meio de itens já feitos correm um alto risco de que eu não os veja, não por desatenção ou falta de atualização na página, mas porque a lista está grande e confusa mesmo. Se tiver alguma sugestão de como melhorar esse fluxo de demandas sou toda ouvidos. Obrigada.

**Comment by laurybueno** [comment]
@ariadnemelo para suas tarefas, eu faço em comentários ou issue nova.

Vou te pedir para apagar dessa lista as tarefas para as quais vc já criou issue

**Comment by laurybueno** [comment]
amigos, estou encerrando esta issue de vez em favor de issues individuais
