### ISSUE TITLE
Ajustar elementos dos cards

### ISSUE THREAD

**Issue by nicolavieira** [hacklabr/paralapraca#356]
Na home de cards, o espaço extra de quando um card tem só uma linha de título deve ficar entre o título e o "publicado por". Assim, todos os elementos do card se alinham com os elementos dos cards vizinhos (quem podem ter títulos de duas linhas)

**Comment by nicolavieira** [comment]
@laurybueno não entendi do que exatamente se trata essa issue. O que é "espaço extra"?

**Comment by laurybueno** [comment]
![screenshot from 2017-09-28 14-49-59](https://user-images.githubusercontent.com/1108897/30981962-5810a300-a45c-11e7-865e-6f113e1f1631.png)

No caso da imagem, por exemplo, o espaço que "sobra" (pq o título tem só uma linha) está indo para a parte de baixo do card. O efeito ruim disso é desalinhar tags e "publicado por" quando vc olha cards lado a lado.

Forçar o espaço que sobra a ficar sempre entre o título e o "publicado por" é a saída que pensei com a cliente. Se vc acha que essa medida deixa o layout mais feio (apesar de desalinhado) eu levo a sua posição para a cliente.
