### ISSUE TITLE
Imagens dentro do editor de galeria devem respeitar o alinhamento da imagem exibida.

### ISSUE THREAD

**Issue by nicolavieira** [hacklabr/paralapraca#358]
Imagens verticais ficam alinhadas à esquerda e lixeira fica ao centro. O vídeo deve ser alinhado ao centro também.

**Comment by nicolavieira** [comment]
Não entendi o que "Imagens dentro do editor de galeria devem respeitar o alinhamento da imagem exibida" quer dizer.

**Comment by laurybueno** [comment]
![screenshot from 2017-10-02 13-48-10](https://user-images.githubusercontent.com/1108897/31088868-7d4ddd76-a778-11e7-84eb-bd9953d9ad3c.png)

Imagens e vídeos no "modo preview" aparecem alinhados à esquerda, enquanto a lixeira logo abaixo aparece alinhada ao centro. Esse problema só é facilmente percebido se a imagem a ser subida é vertical, como no exemplo acima.
