### ISSUE TITLE
Tirar negrito da barra lateral (tanto dos ícones quanto do texto)

### ISSUE THREAD

**Issue by brunopaisano** [hacklabr/paralapraca#36]
Está atrapalhando a legibilidade.

**Comment by nicolavieira** [comment]
@brunopaisano por barra lateral você está se referindo ao menu?

**Comment by brunopaisano** [comment]
Isso! O menu lateral. Eu reparei que as fontes e os ícones estão em negrito. Ou pelo menos parecem estar rs!

**Comment by nicolavieira** [comment]
@brunopaisano os ícones não estão não, por isso que estranhei! mas os links ficam com semi-bold quando o menu está aberto, posso tirar se for o caso.

**Comment by brunopaisano** [comment]
Estranho... olha a diferença entre o implementado e como tá no Sketch:

![captura de tela 2016-08-08 as 14 15 51](https://cloud.githubusercontent.com/assets/20778816/17489141/0fc80786-5d73-11e6-8219-7597e1dc5b66.png)
Implementado

![captura de tela 2016-08-08 as 14 18 30](https://cloud.githubusercontent.com/assets/20778816/17489152/19145d12-5d73-11e6-9db5-55a8265b44f6.png)
Sketch

**Comment by brunopaisano** [comment]
Repara que no bonequinho de "Perfil" nem dá pra ver a divisão entre a cabeça e o corpo no Implementado. O ícone de "Anotações" tá diferente tbm, e no Implementado é um dos que mais me incomodou, pq quase não dá pra ver o lápis.

**Comment by nicolavieira** [comment]
@brunopaisano acho que é um problema de renderização do navegador então, estou mandando um print de como aparece para mim por exemplo:

repare que para mim aparece muito mais próximo com o jeito como está no sketch. o ícone está selecionado e as propriedades ao lado apontam `font-weight: normal`, logo não está em negrito

você está vendo no Mac? qual navegador você usa? chegou a testar em outros navegadores?

![captura de tela de 2016-08-10 14 56 58](https://cloud.githubusercontent.com/assets/2034550/17564799/147f0e66-5f0b-11e6-8070-611a81b8cd5f.png)

**Comment by brunopaisano** [comment]
Tava abrindo no Chrome pra Mac, @ariadnemelo ! Olha só esse teste:

![captura de tela 2016-08-11 as 14 13 46](https://cloud.githubusercontent.com/assets/20778816/17597817/f36c6a20-5fcd-11e6-873d-83ab4d4888f0.png)
Firefox, Safari e Chrome, nessa ordem

Precisamos de um jeito de driblar isso. E de qualquer forma, é preciso:
- [ ] Trocar o ícone de "Anotações" para o que usamos no Sketch (tbm Font Awesome)

**Comment by nicolavieira** [comment]
@brunopaisano  o print que eu mandei é no Chrome também mas no Ubuntu, então é bem estranho ter tanto diferença de renderização

vou dar uma pesquisada e testar no Windows também, pode ser que seja um problema específico do Chrome no Mac

pra troca do ícone queria te pedir pra abrir outra tarefa senão as coisas ficam bagunçadas demais, ok?

**Comment by brunopaisano** [comment]
Beleza, como vcs acharem melhor!

**Comment by nicolavieira** [comment]
![captura de tela de 2016-11-01 07 01 05](https://cloud.githubusercontent.com/assets/2034550/19884558/6cff44ca-a001-11e6-8f37-e6cb1f58db1f.png)
![captura de tela de 2016-11-01 07 01 13](https://cloud.githubusercontent.com/assets/2034550/19884559/6cffe0f6-a001-11e6-9cdb-625528d69309.png)

esses são prints do IE e do Chrome no Windows, o problema parece ser isolado apenas no Chrome do Mac mesmo

passei uma hora pesquisando sobre esse problema no google mas não encontrei ninguém com nada parecido, acho que pra saber se vale a pena investir mais energia nessa tarefa é melhor ver a quantidade de pessoas que acessam o site do Chrome no Mac @brunopaisano

**Comment by brunopaisano** [comment]
@ariadnemelo eu imagino que sejam bem poucas, viu... acho que não compensa gastar energia nisso. Aproveitando, vc chegou a ver que teremos mais opções no menu, né? Serão as opções de administração de "Usuários e grupos" e de "Módulos" (https://zpl.io/ZWM260 | https://zpl.io/16oTHA | https://zpl.io/Z18cdvn | https://zpl.io/2atPNv).

Já fiz uma issue referente a isso, tá aqui: https://github.com/hacklabr/paralapraca/issues/282
