### ISSUE TITLE
Mari não consegue selecionar a tag teste na busca de cards

### ISSUE THREAD

**Issue by nicolavieira** [hacklabr/paralapraca#360]

**Comment by nicolavieira** [comment]
@laurybueno como assim ela não consegue? só acontece com ela?

**Comment by laurybueno** [comment]
essa issue era pra ser pro leo, na verdade.
Seja como for, as tags passaram por muitas mudanças desde então, então vou fechar isso em favor de um report mais estruturado que possa vir no futuro
