### ISSUE TITLE
Botão limpar filtros na busca de cards é necessário

### ISSUE THREAD

**Issue by nicolavieira** [hacklabr/paralapraca#361]

**Comment by nicolavieira** [comment]
@laurybueno Eu coloco o botão lá e depois o @leopiccionia programa o comportamento?

**Comment by laurybueno** [comment]
@ariadnemelo coloca ele comentado no html e avisa o @leopiccionia para adicionar o comportamento. Ele não está disponível hoje, mas ele cuida disso quando voltar à ativa

**Comment by nicolavieira** [comment]
@leopiccionia no branch `fixes-layout` o botão está no arquivo `cards-list.html` comentado a partir da linha 30

**Comment by leopiccionia** [comment]
Botão foi descomentado e está funcionando.
