### ISSUE TITLE
Deixar botões "adicionar imagem" e "adicionar vídeo" mais juntos na tela de edição

### ISSUE THREAD

**Issue by nicolavieira** [hacklabr/paralapraca#365]

**Comment by nicolavieira** [comment]
@laurybueno Mais juntos como? Alinho os dois a esquerda, no meio, ou a direita?

**Comment by laurybueno** [comment]
@ariadnemelo minha primeira ideia é alinhar ao meio, mas vc pode propor algo que considere melhor
