### ISSUE TITLE
Deixar claro de alguma forma que a primeira imagem é a que vai ser usada na home de cards (escrever um texto acima da galeria deve ser o bastante)

### ISSUE THREAD

**Issue by nicolavieira** [hacklabr/paralapraca#366]

**Comment by nicolavieira** [comment]
@laurybueno O cliente deu alguma sugestão de texto ou eu posso escrever qualquer coisa?

**Comment by laurybueno** [comment]
@ariadnemelo o cliente não propôs um texto, mas eu proponho um agora: 

A primeira imagem na galeria abaixo será usada na página inicial do Assim se Faz para divulgar a sua prática
