### ISSUE TITLE
[Cards] Dar um fundo azul para a linha ativa dentro do seletor de tags

### ISSUE THREAD

**Issue by laurybueno** [hacklabr/paralapraca#372]
![screenshot from 2017-10-02 18-34-39](https://user-images.githubusercontent.com/1108897/31100588-66f9cbca-a7a0-11e7-992e-06cdf0fe8268.png)

A inspiração é a tela de novo tópico do Fórum. Tanto lá como no Cards, a item selecionado tem uma classe "active". É possível usá-la para dar estilos a esse item.

Não está claro para mim se essa é a estratégia aplicada na área do fórum, mas é um caminho a ser considerado.

**Comment by nicolavieira** [comment]
@laurybueno testei na base da gambiarra por causa do problema no meu ambiente, se você puder testar na sua máquina e ver se está ok eu agradeço

**Comment by leopiccionia** [comment]
Funcionou!
