### ISSUE TITLE
[Cards] Slide extra que aparece quando a página de edição carrega permite ao usuário passar o limite de 5 slides

### ISSUE THREAD

**Issue by laurybueno** [hacklabr/paralapraca#376]
![screenshot from 2017-10-04 13-44-12](https://user-images.githubusercontent.com/1108897/31188082-33fc8ae4-a90a-11e7-918d-eb6b0c91617d.png)

**Comment by leopiccionia** [comment]
Esse card já tinha sete imagens, é isso?

P.S. De quaquer maneira, o novo branch da galeria não tem esse issue.

**Comment by laurybueno** [comment]
Já tinha sete, e graças a esse estado da galeria, eu podia colocar a oitava. Carregando de novo a página, posso colocar a nona e assim por diante.

Quanto tempo até esse refactor estar pronto?

(refs #370)
