### ISSUE TITLE
Colocar o scroll no widget do fórum e deixar a lista de “últimas postagens” com somente 4 linhas aparecendo

### ISSUE THREAD

**Issue by brunopaisano** [hacklabr/paralapraca#38]
Senão, não faz nem muito sentido ter outra tela só pro fórum que a não ser isolar a informação. Podemos pensar na mesma lógica do widget dos módulos e colocar um botão “mostrar todos”, se necessário/preferível.

**Comment by nicolavieira** [comment]
@brunosmartin nós não temos scroll funcionando porque deixamos isso para depois, então precisamos ver o que fazer, que plugin usar... na época não achei nenhum que fosse nativo do angular, todos eram port de plugin em jquery

**Comment by brunosmartin** [comment]
Segura esta que eu quero disccutir melhor. Não concordo muito com estes scrolls não, queria pensar melhor sobre isso.
