### ISSUE TITLE
[Cards] Área de texto de tags não precisa ter contorno azul enquanto está selecionada

### ISSUE THREAD

**Issue by laurybueno** [hacklabr/paralapraca#383]
![screenshot from 2017-10-10 14-35-13](https://user-images.githubusercontent.com/1108897/31401136-5050c508-adc8-11e7-8280-cbd76e5760d8.png)

**Comment by leopiccionia** [comment]
Em que navegador ocorreu o *report*? Tanto localmente quanto na produção (AVA), tanto no Firefox quanto no Chrome, a caixa de sugestões do `ui-select`ocupa 100% da largura da caixa de texto, o que não deixa nenhum contorno azul visível (vide #382).
