### ISSUE TITLE
[Users] Novos usuários se cadastram com CPF, mas o mesmo não aparece na tela de edição de perfil

### ISSUE THREAD

**Issue by laurybueno** [hacklabr/paralapraca#386]
![screenshot from 2017-10-10 14-45-40](https://user-images.githubusercontent.com/1108897/31401606-caa45c42-adc9-11e7-9d60-4e93c9c79585.png)

**Comment by virgilio** [comment]
Durante o fix do signup da home eu ajeitei esse formulário.

**Comment by laurybueno** [comment]
ótimo. Esta issue pode ser fechada quando você preferir, Virgílio
