### ISSUE TITLE
[Signup] Campo email não deve permitir caracteres inválidos

### ISSUE THREAD

**Issue by laurybueno** [hacklabr/paralapraca#387]
"ç" é um exemplo de letra aceita incorretamente

**Comment by virgilio** [comment]
Já tem uma validação nativa do navegador, colocar uma via JS?

**Comment by laurybueno** [comment]
acho que o campo nem é to type email ainda. Só isso, já resolve bem imagino.

**Comment by virgilio** [comment]
No signup (em /accounts/signup ) é, no login, não (até porque é email/username)... Uma pergunta, qual página dá acesso ao signup? eu só consigo entrar pelo link direto da url de accounts, não achei nenhum link que chega nela.

**Comment by laurybueno** [comment]
o type do campo é email e ele permite caracteres como "ç"? Essa é nova pra mim. Talvez, JS seja o caminho então (validação no django também é aceitável)

Nós não temos um signup aberto mesmo. O cliente manda a URL diretamente para possíveis interessados.

**Comment by leopiccionia** [comment]
Aparentemente, o que o Django estava fazendo era converter UTF8 em Punycode. Alguns provedores de email permitem caracteres UTF8 tanto antes quanto depois da arroba (há RFCs nesse sentido), precisa ver se suportamos isso.

**Comment by virgilio** [comment]
Opa, isso aí é ainda outra questão, olha só:
https://i.imgur.com/iFCIIL6.png

Aqui ele não deixa dar submit

**Comment by laurybueno** [comment]
parece que antes do @ ele não deixa e depois deixa

**Comment by laurybueno** [comment]
@virgilio dá uma olhada no usuário `laurylaury` na produção. Ele tem o ç depois do @. Vê em que telas isso é um problema (acho que é na edição de perfil)

**Comment by virgilio** [comment]
Eu testei, localmente, o signup e o edit e rolou tranquilo. o laurylaury no django admin tá lá com a ç, o que teríamos que fazer pra testar é arrumar um server que tenha caracter especial no nome e ver se o django consegue enviar o e-mail:

'''
web_1  | MIME-Version: 1.0
web_1  | Content-Type: text/plain; charset="utf-8"
web_1  | Content-Transfer-Encoding: 8bit
web_1  | Subject: =?utf-8?q?Registo_no_Paralaprac=C3=A1?=
web_1  | From: paralapraca-nao-responda@ava.paralapraca.org.br
web_1  | To: virgilio@xn--elko-zoa8e.com
web_1  | Date: Thu, 19 Oct 2017 17:25:13 -0000
web_1  | Message-ID: <20171019172513.45.23732@85706f5c61f6>
web_1  | 
web_1  | Caro(a), bem vindo(a) ao Paralapracá!
web_1  | 
web_1  | Estamos felizes por poder ajudá-lo(a) nesse trajeto de reflexão e aprendizado.
web_1  | 
web_1  | Para garantir que você tenha acesso a todos os recursos e cursos que temos para oferecer, clique no link abaixo e confirme o seu endereço de e-mail.
web_1  | 
web_1  | http://localhost:8000/accounts/confirm-email/ue0kjgxnxl4lepexpu9h2ayqmhglqbmafzbkol3e24hh5p31y9kp9pwhbapg3h3s/
web_1  | 
web_1  | 
web_1  | Até já!
web_1  | Avante e Instituto C&A
'''

**Comment by laurybueno** [comment]
@virgilio, era para ter um "ç" nesse email. Ele não aparece. Essa é a tela de edição de perfil do `laurylaury`

![screenshot from 2017-10-19 15-34-06](https://user-images.githubusercontent.com/1108897/31785156-07afb74c-b4e3-11e7-9bbe-fb925f21f229.png)

**Comment by virgilio** [comment]
Eu testei localmente o signup e o edit e funcionou. Mas precisaríamos achar um servidor que tenha caracter especial pra ver como se comporta o envio de e-mail, exceto por isso, não parece haver problemas naquele form. (eu mandei outra mensagem e apaguei sem querer, vcs devem ter recebido por email)

**Comment by virgilio** [comment]
Testarei

**Comment by virgilio** [comment]
Agora ficou bem isolada, no admin tá correto, então, é só na tela mesmo, valeu!

**Comment by virgilio** [comment]
@laurybueno eu não estou conseguindo reproduzir em http://ava.paralapraca.org.br,
![config_account_ava.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5550afe55a5af065004fdcff/125516c66e82c728ace21e0d46eb9b94258b84968eeabc4cb153e4ab285026316546b3397f8fe62bab0021435a5847fe480a0e40aafe802aaeb03d738a5c59bed13c0a72d42103eee9dc4be05ce36ade0d97bcae8b45cae93825ee8b8b4a371c061888f74f78.png)

**Comment by virgilio** [comment]
No localhost a mesma coisa, ç entra no sistema normal e é apresentada normalmente

**Comment by laurybueno** [comment]
Deve estar correto já então.
