### ISSUE TITLE
[Home] [Responsivo] Logo aparece como uma linha a mais no header

### ISSUE THREAD

**Issue by laurybueno** [hacklabr/paralapraca#388]
![screenshot from 2017-10-10 14-50-53](https://user-images.githubusercontent.com/1108897/31401889-a72ec3f0-adca-11e7-8eb2-2ac2f6eec247.png)

**Comment by leopiccionia** [comment]
E a linha com os animais? Fica lá mesmo ou sobe com o resto do logo?

**Comment by laurybueno** [comment]
não só a linha com os animais precisa subir, como também todo o layout. Não podemos só subir o logo e deixar o espaço em branco onde ele estava
