### ISSUE TITLE
[widget fórum] Ajustar padrão dos marcadores “X responderam” e “X gostaram” em “últimas postagens”

### ISSUE THREAD

**Issue by brunopaisano** [hacklabr/paralapraca#39]
Texto e ícone em laranja se n > 0, texto e ícone em cinza se n = 0.

**Comment by nicolavieira** [comment]
@brunopaisano essa issue se refere a #43?

**Comment by brunopaisano** [comment]
Refere-se ao widget do fórum na verdade, @ariadnemelo ! Mudei o título para ficar mais claro :)

**Comment by nicolavieira** [comment]
@brunopaisano entendi, mas a regra é a mesma, certo? vou fechar essa e especificar na outra tarefa, ok?
