### ISSUE TITLE
[Home] [Contato] [Responsivo] Após envio de email, o ícone 'menu' fica em cima do logo

### ISSUE THREAD

**Issue by laurybueno** [hacklabr/paralapraca#396]
![screenshot from 2017-10-10 15-13-50](https://user-images.githubusercontent.com/1108897/31402896-c93df38c-adcd-11e7-9703-7c0f9ce68df4.png)

**Comment by leopiccionia** [comment]
Após fechamento do modal, a tag `body` ganha um `position: relative` que efetivamente quebra o layout.

Não tendo conseguido encontrar a razão de tal comportamento dentro da aplicação, suspeito que a causa de tal fenômeno sejam as próprias rotinas de jQuery/Bootstrap.js responsáveis pela manipulação do modal.

Minha proposição nesse caso, que se encontra no branch `issue#396`, é sobrepor tal comportamento definindo `position: absolute !important` em telas pequenas.
