### ISSUE TITLE
[Edição de Perfil] Mudar senha desloga usuário sem nenhuma notificação de sucesso ou fracasso

### ISSUE THREAD

**Issue by laurybueno** [hacklabr/paralapraca#400]
Idealmente, o logout não aconteceria. No limite, o usuário deve ser notificado antes disso.

**Comment by virgilio** [comment]
https://docs.djangoproject.com/en/1.8/topics/auth/default/#session-invalidation-on-password-change

https://docs.djangoproject.com/en/1.8/releases/1.7/#django-contrib-auth

**Comment by laurybueno** [comment]
Abordagem escolhida foi não deslogar o usuário após a mudança de senha
