### ISSUE TITLE
[Edição de Perfil] Foto de perfil pode desaparecer quando ela é trocada, mas há algum erro de validação no formulário ao mesmo tempo

### ISSUE THREAD

**Issue by laurybueno** [hacklabr/paralapraca#402]

**Comment by laurybueno** [comment]
@virgilio acho que ainda não foi, cara.
Mudei a foto e troquei um campo para formato inválido, daí quando tudo recarregou, nada apareceu na área de foto

![Screenshot from 2017-10-24 19-13-31.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579b995b0691021300ca7a0c/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227e49f27b3dd7b768ee1b36505c424dad53444d04bea6d37ef5f22e7a98590ce483640d25c26b16a5b98a19be02ba20d91c85e7e98c5edcfa7f74b9dfd0126754505a9bf54f34a7934acd58fe43e64452a0163363e6647b.png)

**Comment by laurybueno** [comment]
eu tinha feito o teste acima sem mudar de branchs (timtec e paralapraca)

Agora, eu mudei, mas o comportamento continua ruim. eu vi que ele não permite mais que o campo CPF fique vazio, mas isso não é a solução, porque há outros erros de validação possíveis nesse campo.

Achei que tínhamos optado por fazer a foto original voltar a aparecer após um erro de validação. Entendi errado?

**Comment by virgilio** [comment]
No caso, deixa só a validação de servidor? tiro o required dos campos?
