### ISSUE TITLE
[Dashboard] Angular faz uma requisição POST desnecessária à API de curso quando a página carrega

### ISSUE THREAD

**Issue by laurybueno** [hacklabr/paralapraca#403]

**Comment by leopiccionia** [comment]
Eis o resultado de minhas investigações: o que causava o erro, na verdade, é que (como confirma a documentação do código) a solicitação deveria ser `OPTIONS`, não `POST`, e alterar o método HTTP corrige o problema.

Essa requisição servia para obter as descrições dos campos da API, a fim de se exibir mensagens de erro mais específicas para os usuários. Não há problemas em remover a requisição, pois a função de geração de mensagens de erro tem o *fallback* de exibir mensagens de erro genéricas caso a requisição falhe -- atualmente, com o método `POST`, a função usa esse *fallback*.

**Comment by leopiccionia** [comment]
Troquei a ordem da importação dos arquivos *.js no branch `imports-order`. Superficialmente, parece que tudo funciona, mas sugiro uma inspeção mais profunda antes do *release*.

**Comment by leopiccionia** [comment]
Foi alarme falso, a requisição continua sendo feita.

E não me parece haver muito o que se fazer: a requisição AJAX é feita dentro da `factory`. Sempre que ela é instanciada (lembrando que ela é um *singleton*), a requisição é chamada.

Eu consigo pensar em duas soluções para o problema:
1. Remover definitivamente essa `factory` `Course`. Remover ela não quebra o *dashboard* -- o próximo passo é descobrir quem mais usa ela, para fazer uma remoção com segurança.
2. Fazer com que a `factory` deixe de ser usada. Eu pensei ter feito isso, mas parece que não?

Por qual caminho prosseguir?

**Comment by leopiccionia** [comment]
Estou fechando essa issue porque, devido a alterações no dashboard, eu não consigo mais reproduzi-la, ou seja, o problema foi provavelmente sanado.
