### ISSUE TITLE
Tags Angular de template podem aparecer em seu formato "raw" em determinados casos 

### ISSUE THREAD

**Issue by laurybueno** [hacklabr/paralapraca#404]
Lentidão de processamento da máquina ou da internet parecem ser fatores que favorecem o aparecimento do erro.

**Comment by leopiccionia** [comment]
Você tem exemplo de alguma página em que isso ocorre? O padrão do repositório parece ser colocar as tags `<script>` acima da borda, bloqueando toda a renderização do HTML até o JS ser carregado.

De qualquer maneira, quando arrumar tempo, posso verificar página a página.

**Comment by leopiccionia** [comment]
Repito que ainda não consigo reproduzir o problema.

No entanto, olhando o projeto, percebo que utilizamos a diretiva `ng-cloak` conforme recomendação da documentação oficial. Um expediente que podemos adicionalmente utilizar é substituir as templates Angular `{{ ... }}` pela diretiva `ng-bind`. Estimo que, se seguirmos por esse caminho, precisaríamos modificar o código em 500 a 1000 lugares.

**Comment by laurybueno** [comment]
@leopiccionia esse sempre foi um problema de reprodução difícil mesmo. Já vi acontecer em celulares e no meu próprio computador sem padrões aparentes.

Levando em conta a dificuldade de reprodução e a provável atualização do frontend do Timtec para Angular 5 nos próximos meses, estou fechando esta issue.

Se encontrarmos novos elementos que nos ajudem a decifrar este problema, podemos reabrí-la.
