### ISSUE TITLE
[Dashboard] [Responsivo] Imagens de cursos devem respeitar as proporções usadas em outros lugares da plataforma

### ISSUE THREAD

**Issue by laurybueno** [hacklabr/paralapraca#405]
Como a proporção da imagem varia dependendo da largura do dispositivo usado, imagens podem ser cortadas.

![screenshot from 2017-10-10 15-49-32](https://user-images.githubusercontent.com/1108897/31404739-3cb5dc30-add3-11e7-9d46-b404953a59bb.png)

**Comment by leopiccionia** [comment]
Corrigido no branch `issue#443`.
