### ISSUE TITLE
[Notificações] Animação de loading deve aparecer na parte de dentro da área de notificações (e não de fora)

### ISSUE THREAD

**Issue by laurybueno** [hacklabr/paralapraca#406]
![screenshot from 2017-10-10 16-06-38](https://user-images.githubusercontent.com/1108897/31405878-b325ddc8-add5-11e7-9baf-b7fb48a2bd81.png)

**Comment by leopiccionia** [comment]
Por *design*, a implementação do `angular-loading-bar`não permite mais de uma instância na página (vide [aqui](https://github.com/chieffancypants/angular-loading-bar/issues/169) e [aqui](https://github.com/chieffancypants/angular-loading-bar/issues/44)). O que é possível, no entanto, é fazer com que apenas o serviço `Notifications` não engatilhe o `angular-loading-bar`, sem prejuízo aos demais serviços.

**Comment by laurybueno** [comment]
Impedir que o angular-loading-bar acione a animação para os serviços de notificação é uma parte da resposta. (inclusive, eu tentei fazer isso há muito tempo, mas não rolou. Não acho que seja difícil, eu só devo ter esquecido algum pulo do gato na época)

A outra parte é dar uma animação de carregando especificamente para essa área interna da aba de notificações (a exemplo da animação de carregamento do tinymce,  suponho).
