### ISSUE TITLE
[SlidesRevealActivity] Encontrar uma forma de impedir que o iframe dos slides capture os eventos de touch (pelo menos os verticais)

### ISSUE THREAD

**Issue by laurybueno** [hacklabr/paralapraca#416]
Essa captura de eventos dificulta a navegação no AVA em celulares, já que o scroll da página fica comprometido.

**Comment by leopiccionia** [comment]
Corrigido no branch `issue#443`.

Um side-effect é que não é mais possível avançar e retroceder slides via gesto de *swipe*.
