### ISSUE TITLE
Ajustar proporções na tela “Módulos” de acordo com a tela no Zeplin

### ISSUE THREAD

**Issue by brunopaisano** [hacklabr/paralapraca#42]
Tamanhos de fonte, tamanho das thumbnails de cada módulo, informações abaixo do título, inserir barra de porcentagem de conclusão, mudar cor da label na parte debaixo da thumbnail para verde (em caso de curso não-iniciado).

**Comment by nicolavieira** [comment]
@brunopaisano segundo essa tela? https://app.zeplin.io/project.html#pid=576ad22a40ea7eb4350a160f&sid=579a7b896593991f6932e6ed

**Comment by brunopaisano** [comment]
Isso, @ariadnemelo ! Essa mesmo!
