### ISSUE TITLE
[Forum] Breadcrumbs devem ser clicáveis na página de tópico

### ISSUE THREAD

**Issue by laurybueno** [hacklabr/paralapraca#421]
![screenshot from 2017-10-10 17-28-17](https://user-images.githubusercontent.com/1108897/31408952-930d1e56-ade0-11e7-97b1-6b45b09a6c5e.png)

**Comment by leopiccionia** [comment]
Mesmo comentário em relação ao issue #423.

**Comment by laurybueno** [comment]
Esta issue fica pendente por depender do mesmo fix necessário para a #423
