### ISSUE TITLE
[Fórum] [Responsivo] Há páginas demais disponíveis e o layout quebra no mobile

### ISSUE THREAD

**Issue by laurybueno** [hacklabr/paralapraca#422]
![screenshot from 2017-10-10 17-30-46](https://user-images.githubusercontent.com/1108897/31409155-5222cade-ade1-11e7-9390-2fcc256b1771.png)

**Comment by leopiccionia** [comment]
Alguma sugestão a respeito de como fazer isso? Eu pensei em ter o botão de primeira página, página anterior, página atual, próxima página, última página.

**Comment by laurybueno** [comment]
no mundo ideal, esse componente de paginação mostraria menos números de páginas dependendo da largura de tela disponível.

há algo nesse sentido na documentação?

**Comment by leopiccionia** [comment]
Responsivamente, não é possível, mas dá para fazer adaptativamente.

Eu fui buscar inspiração no BootstrapVue, que exibe apenas três páginas em telas XS. É possível construirmos algo assim, testando o melhor tamanho para cada tamanho de tela.

![Captura de tela de 2017-10-23 10-00-25.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57a78bb0e5e72d0e0023b82e/125516c66e82c728ace21e0d46cb958a379791a8cfedba03b058fc95694222337b54f27c3dd4b365ed113b505f424eac5c5a5a56e0ebc969f9ec6923ce4e01ffd46a5626cf6f40a8ee8516be09bc21884f85e4ef8a1d95ee2f39f5c9de116a415841c3aa1f27aa8b49c952f74ee14552a213356be672317f55d9.png)
