### ISSUE TITLE
[Forum] [Responsivo] Breadcrumbs na home de fórum devem ser clicáveis e botão 'opções' deve ser substituído por "criar novo tópico"

### ISSUE THREAD

**Issue by laurybueno** [hacklabr/paralapraca#423]
![screenshot from 2017-10-10 17-35-07](https://user-images.githubusercontent.com/1108897/31409239-8ebcf032-ade1-11e7-8096-f61d0b29855b.png)

**Comment by leopiccionia** [comment]
Em relação a esse issue, bem como o #421, como fica a questão dos filtros de busca dos fóruns?

Manter os filtros antigos ou ignorá-los? No primeiro caso, a escolha por filtros nas URLs começa a cobrar um preço caro.

**Comment by laurybueno** [comment]
Os filtros antigos podem ser ignorados. Eles não precisam fazer parte do link nesses breadcrumbs

**Comment by leopiccionia** [comment]
No momento, eu não vou substituir o menu por um único botão de criação de tópico porque isso quebraria *layouts* em tamanhos de tela que comportam a versão atual:

![image](https://user-images.githubusercontent.com/9576518/31665128-a3ac91ba-b326-11e7-975c-a138cac5064a.png)

**Comment by leopiccionia** [comment]
@ariadnemelo Agora que os breadcrumbs são clicáveis, precisamos de um CSS para que os links mantenham a cor laranja.

P.S. O mesmo se aplica ao issue #421, que também trata de breadcrumbs.

**Comment by laurybueno** [comment]
O link para ao home de Fórum está apontando para `/discussion/`, o que quebra a aplicação angular quando clicado. As alternativas são linkar para `/discussion/home/` ou `/discussion/#!/`. A segunda opção é preferível se ela não quebrar a aplicação também.
