### ISSUE TITLE
[Forum] Enquanto o editor TinyMCE não carregar, alguma animação de "loading" deve ser exibida

### ISSUE THREAD

**Issue by laurybueno** [hacklabr/paralapraca#424]
Esse feature é especialmente útil em página como essa: http://ava.paralapraca.org.br/discussion/topic/#!/topic/4464/

![screenshot from 2017-10-10 17-40-55](https://user-images.githubusercontent.com/1108897/31409542-abe2ed14-ade2-11e7-8c4d-fbdd9f99accf.png)

**Comment by leopiccionia** [comment]
Pesquisando um pouco, parece que o jeito correto de se fazer isso é editar a própria configuração do TinyMCE.

https://www.tinymce.com/docs/advanced/events/#init
https://stackoverflow.com/questions/11538231/using-a-pre-loader-image-to-hide-tinymce-source-code-till-the-content-loads/11538682#11538682

**Comment by leopiccionia** [comment]
@ariadnemelo Falta estilizar o spinner. Sugiro centralizá-lo, talvez colocar a mesma cor dos outros spinners.

P.S. A alteração está no branch `forum-breadcrumbs`, também. Para visualizar o *spinner*,  sugiro simular lentidão na rede. Se precisar de ajuda com isso, é só comentar.

**Comment by laurybueno** [comment]
@leopiccionia essa animação de loading também foi aplicada aos outros editores tinymce da página? (há mais um que me lembro agora: o editor de resposta a comentário)

**Comment by leopiccionia** [comment]
O do topo da página deve ser o único.

Os outros não devem causar a mesma estranheza, mas posso estudar como aplicar a animação aos demais.
