### ISSUE TITLE
[Forum] Módulo de exibição de anexos em tópicos fica rapidamente duplicado quando é aberto

### ISSUE THREAD

**Issue by laurybueno** [hacklabr/paralapraca#425]
![peek 2017-10-10 17-47](https://user-images.githubusercontent.com/1108897/31409790-6fcd773a-ade3-11e7-97ae-2b87099a0e93.gif)

**Comment by leopiccionia** [comment]
Para referência futura: o problema parece ser um *side effect* do `ngAnimate` (durante alguns *keyframes*, ambas animações exibem o botão). Uma solução que não envolve CSS é envolver os elementos em `div`s externas.
