### ISSUE TITLE
[Forum] Erros de formulário não são notificados adequadamente na tela de criação de tópico

### ISSUE THREAD

**Issue by laurybueno** [hacklabr/paralapraca#429]

**Comment by laurybueno** [comment]
esse fix está em algum branch específico? Não parece funcionar no master  de django-discussion e paralapraca

**Comment by laurybueno** [comment]
Agora, eu vi que os erros aparecem em cima. Se eles vão ficar lá, um scroll para o topo é necessário. 

Você pode usar o mesmo método da atividade discussão.

**Comment by leopiccionia** [comment]
Vou corrigir isso hoje.
