### ISSUE TITLE
Página inicial do fórum

### ISSUE THREAD

**Issue by brunopaisano** [hacklabr/paralapraca#43]
- [x] 1. Ajustar padrão dos marcadores “X responderam” e “X gostaram” em “últimas postagens”. Texto e ícone em laranja se n > 0, texto e ícone em cinza se n = 0. Ver também no widget do fórum (issue #39). 
- [x] 2. Ajustar espaçamento entre título do fórum e lista de tópicos
- [x] 3. Travar o espaçamento entre as colunas da lista de tópicos dos fóruns de acordo com a tela no Zeplin, para que não fique desajustado com pouca/nenhuma informação em alguma das colunas (tópico – reações – categoria – tags)
- [x] 4. Padronizar espaçamento entre listas de fóruns diferentes
- [ ] 5. Inserir a opção de “ocultar” e “mostrar”

**Comment by nicolavieira** [comment]
@brunopaisano pode especificar melhor ou colocar print dos ajustes 2, 3 e 4? não sei exatamente do que você está falando

**Comment by brunopaisano** [comment]
Explico melhor. Vou fazer um comentário pra cada tópico que vc teve dúvida.

Tópico 2
link no Zeplin: https://zpl.io/1cIrTH (tela mais semelhante a como está implementado)
print de como está implementado:
![captura de tela 2016-08-02 as 16 33 16](https://cloud.githubusercontent.com/assets/20778816/17342292/f767dcb4-58ce-11e6-8361-fee91a53470a.png)

O espaço entre o título (no print, "fórum assessoras") e a lista (até a palavra "tópico") está um pouco grande demais. Pode ser menor. E tbm, seria legal alinhar a palavra "tópico" aos nomes dos tópicos, e não ao título.

**Comment by brunopaisano** [comment]
Tópico 3

link no Zeplin: https://zpl.io/1cIrTH (tela mais semelhante a como está implementado)
print de como está implementado:
![captura de tela 2016-08-02 as 16 40 18](https://cloud.githubusercontent.com/assets/20778816/17342494/f7917fa0-58cf-11e6-9abf-370477f31363.png)

A largura da coluna "tópico" está muito maior que a das outras, que estão muito estreitas. Projetamos ela menor no Sketch pra dar mais espaço no caso de muitas tags, por exemplo. Do jeito que está, caberia só uma tag, no máximo duas.

**Comment by brunopaisano** [comment]
Tópico 4

Já foi resolvido, desencana hehe!

**Comment by nicolavieira** [comment]
valeu @brunopaisano! ;)

**Comment by nicolavieira** [comment]
vou fechar essa tarefa e abrir outra para os botões de ocultar/mostrar
