### ISSUE TITLE
Página de tópico

### ISSUE THREAD

**Issue by brunopaisano** [hacklabr/paralapraca#44]
O título “comentários” deve iniciar com minúscula (aqui e em todas as telas em que estiver).

**Comment by nicolavieira** [comment]
@brunopaisano não entendi, pode especificar melhor?

**Comment by brunopaisano** [comment]
Editei, @ariadnemelo ! Entendeu?

**Comment by nicolavieira** [comment]
@brunopaisano sim, agradeço!
