### ISSUE TITLE
[Fóruns] Filtragem por contratos

### ISSUE THREAD

**Issue by leopiccionia** [hacklabr/paralapraca#453]
Algumas considerações necessárias para integrarmos a noção de contratos a `django-discussion`, em ordem aproximada de prioridades:
- [ ] A API de fóruns deve retornar um campo `contract`.
- [ ] Permitir a filtragem de fóruns (e não tópicos) por contrato. O parâmetro pode ser um `id` ou, se optarmos por um filtro multi-valorado, uma *array* de `id`s.
- [ ] Talvez aplicar o mesmo filtro do item (2) na API das últimas postagens (pessoalmente, acho não prioritário).

**Comment by virgilio** [comment]
Regra análoga a relação de usuários com fóruns

**Comment by virgilio** [comment]
- [x] Para tela de administração, teremos o mesmo filtro

**Comment by virgilio** [comment]
- [ ] ~A API de fóruns deve retornar um campo `contract`.~
- [ ] A API será capaz de filtrar os forums por contrato, passado como variável de filtro no método GET
- [x] Permitir a filtragem de fóruns (e não tópicos) por contrato. O parâmetro pode ser um `id` ou, se optarmos por um filtro multi-valorado, uma *array* de `id`s.
- [ ] Talvez aplicar o mesmo filtro do item (2) na API das últimas postagens (pessoalmente, acho não prioritário).
