### ISSUE TITLE
Mudar a cor do e texto do botão "Continuar Módulo" quando ele ainda não tiver sido iniciado.

### ISSUE THREAD

**Issue by helenalb** [hacklabr/paralapraca#46]
Mudar a cor do e texto do botão "Continuar Módulo" quando ele ainda não tiver sido iniciado, para algo como "Iniciar" em verde
![captura de tela de 2016-08-02 15-00-13](https://cloud.githubusercontent.com/assets/20777077/17339460/639ab88c-58c2-11e6-810c-6c55df0e1bb2.png)

**Comment by nicolavieira** [comment]
@brunosmartin tem dois ifs lá, o `ng-if="course.course_student===undefined"` é quando o usuário ainda não começou o curso?

**Comment by brunosmartin** [comment]
Removi a tag back end pq já tem esta lógica no template, usando angular.
