### ISSUE TITLE
[Reports] Acrescentar coluna município aos relatórios "por grupos" e "por turmas" (estratégia de grupos com nome exato do município)

### ISSUE THREAD

**Issue by laurybueno** [hacklabr/paralapraca#461]

**Comment by tiagofassoni** [comment]
Dentro do contrato, tem um arrayfield. Esse arrayfield tem todos os nomes de cidades pertencentes ao contrato.

Aí procuro os grupos cujo nome dá match exato com o arrayfield do contrato. Os que derem match são as cidades.

**Comment by tiagofassoni** [comment]
@virgilio Está commitado no master agora, você pode só dar uma olhada lá nos endpoints `http://127.0.0.1:8000/paralapraca/api/users-by-class` e `http://127.0.0.1:8000/paralapraca/api/users-by-group` para ver se tá do agrado?
