### ISSUE TITLE
[Perfil] Admins devem ser capazes de editar perfil de outros usuários

### ISSUE THREAD

**Issue by laurybueno** [hacklabr/paralapraca#463]

**Comment by virgilio** [comment]
Aceitação:
1. Usuário administrador: 
  1.1. Acessa o perfil de cada aluno pela lista do menu Administração -> Usuários
  1.2. Acessa o perfil de um aluno com o link do perfil do mesmo 
  1.3. No perfil, acessa botão para edição de usuário no canto direito da tela
  1.4. Edita e salva dados de acordo com as validações necessárias (testar todas)
  1.5. Testar mudança de senha
2. Usuário comum
  2.1. Não tem acesso aos menus de Administração
  2.2. Recebe uma tela de forbbiden ao acessar link direto de edição de usuário
  2.3. Ao acessar perfil de usuário se for o seu próprio, vê botão verde de edição, caso não, não vê nenhum botão
3. Todas as telas do item 1 terão borda dashed 1px vermelha e alerta de confirmação antes de qualquer alteração de dados
