### ISSUE TITLE
Implementar a possibilidade de um curso ter mais de um template de certificado

### ISSUE THREAD

**Issue by laurybueno** [hacklabr/paralapraca#469]
Cada template deve estar associado a uma ou mais turmas, mas uma turma só pode estar associada a um dos templates existentes.

- [x] Alterar modelos e criar migrações de dados
- [x] Criar tela de listagem de templates de certificados
- [x] Criar endpoint de listagem de templates de certificados
- [x] ~Possibilitar relacionar uma ou mais turmas ao template de certificado sendo editado~
- [x] ~Adaptar endpoint do template de certificado para aceitar associação com diversas turmas~

Depende da issue #470.

**Comment by virgilio** [comment]
- [x] Separar tela de edição de certificado que desvincula os dois tipos templates
- [x] Criar tela de preview de certificado
- [x] Criar forma para exclusão de imagens do certificado
- [x] Criar redirecionamento entre urls originais e exclusivas do plpc
- [x] Tirar link de tela de edição de curso (o contrato agora associa cursos/contratos/tipo)
- [x] Alterar tela de exibição de certificado/receipt para assumir nova estrutuda de dados
- [x] Criar filtros na tela de listagem de templates e link para geração de templates por curso/contrato
- [x] Criar ajuda para edição de certificados
- [x] Criar script para atualização de dados
