### ISSUE TITLE
Página de aula (módulo)

### ISSUE THREAD

**Issue by brunopaisano** [hacklabr/paralapraca#47]
Ajustar a marcação das unidades (timeline abaixo da barra amarela) de acordo com a tela no Zeplin:
- Unidades feitas em laranja
- Unidade sendo feitas no momento em laranja e em tamanho maior
- Unidades a fazer em cinza

Atualmente está num tom de cinza diferente do da tela no Zeplin, e as unidades a fazer também estão em laranja, por isso o pouco contraste.

**Comment by nicolavieira** [comment]
As classes no css já existem, precisa apenas criar uma regra que aplique as classes certas. `current` demarca a unidade atual e `done` as unidades já feitas. Para as unidades a fazer é só deixar apenas a classe `unit`.

**Comment by nicolavieira** [comment]
atualizar o layout conforme: https://zpl.io/KCKNd

**Comment by brunosmartin** [comment]
A parte de backend eu arrumei ontem, é só acertar os estilos.

**Comment by brunopaisano** [comment]
- [ ] Na página "Todos os módulos", alinhar o título dos módulos ao topo da thumbnail no caso dos cursos que ainda não foram começados. 

Acredito que, apesar de não ter barra de conclusão (já que o curso não foi iniciado), a div da barra ainda está lá.

**Comment by nicolavieira** [comment]
me avisem se puder fechar essa issue por favor

**Comment by brunopaisano** [comment]
Ainda não, Ari! A linha por trás das bolinhas, a partir da unidade que está sendo feita, deve ser cinza, e não laranja.

**Comment by brunosmartin** [comment]
Bruno, vamos conversar isso melhor, pq nao rola do laranja ir acompanhando
as bolinhas , pq o usuário pode pular uma unidade. Vamos deixar com esta
por hora

Em 8 de ago de 2016 16:55, "Bruno Souza" notifications@github.com
escreveu:

**Comment by brunopaisano** [comment]
Por enquanto não vejo problema. Se o usuário pular uma ou várias unidades, o laranja acompanha até a unidade pra qual ele pulou. Mas tudo bem, conversamos melhor amanhã!

**Comment by nicolavieira** [comment]
@brunopaisano @brunosmartin  estou fechando essa e vou abrir outra para discutir somente a barra de progresso
