### ISSUE TITLE
Trocar background do AVA como um todo para a imagem que está no Zeplin (ou semelhante)

### ISSUE THREAD

**Issue by brunopaisano** [hacklabr/paralapraca#48]
O pattern atual tá com um ruído que faz dar pra sacar que tá replicado. Se tiver como colocar o mesmo que usamos no Sketch é massa; senão, colocar um que não deixe esse ruído. Eu e Luis podemos ajudar, se precisar :)

**Comment by brunosmartin** [comment]
Bruno, melhora a descrição do título. Quando a gente bate o olho no título, temos q saber do que se trata sem entrar e ler a descrição

**Comment by nicolavieira** [comment]
o que está agora é só um teste mesmo, só preciso que me enviem o arquivo da imagem correta para fazer a troca

**Comment by brunopaisano** [comment]
O @luisfbs vai te enviar o fundo, @ariadnemelo !

**Comment by brunopaisano** [comment]
![seamlesstexture4_1200](https://cloud.githubusercontent.com/assets/20778816/17342734/e4be1bf8-58d0-11e6-8603-c33c3019b6f8.jpg)

**Comment by nicolavieira** [comment]
@brunosmartin eu já troquei o fundo, porque foi reaberta?

**Comment by brunopaisano** [comment]
@ariadnemelo , aproveitando que foi reaberta (não sei o motivo), tem um ajuste:
- [ ] Colocar o fundo em 60% de opacidade

Fizemos assim no Sketch :)

**Comment by nicolavieira** [comment]
@brunopaisano só é possível deixar fundo transparente quando é cor, quando é imagem não tem como fazer isso pelo css, então vou precisar que vocês me mandem a imagem com a transparência correta, tudo bem?

**Comment by brunopaisano** [comment]
https://drive.google.com/open?id=0B41LgNNlR6cvcHJKQndvM1B0dEU

Segue, @ariadnemelo !

**Comment by brunosmartin** [comment]
Pessoal, imagens com transparência não devem ser usadas como backgroud pois tendem a ficar muito grande. Esta, po exemplo, tem 2,6 MB, o que é muito grande. O tamanho ideal desta imagem é ser menor que 200 KB, mas no máximo dos máximos (não é bom) uns 400KB.

**Comment by nicolavieira** [comment]
Acho que eu não fui muito específica mesmo, mas a idéia era colocar a transparência, salvar a imagem em cima de um fundo branco e mandar como jpg. Fiz isso aqui no gimp e depois queria que você me dissesse se está ok @brunopaisano. A imagem está com 130kb ;) @brunosmartin

**Comment by brunopaisano** [comment]
@ariadnemelo , já posso ver? Se sim, coloca o link aqui pra mim, pls?

**Comment by nicolavieira** [comment]
@brunopaisano pelo o que conferi ainda não esta mesmo no ambiente de teste, mas esse é um print de como ficou no meu local 
![captura de tela de 2016-08-11 14 31 56](https://cloud.githubusercontent.com/assets/2034550/17598366/87d7f10a-5fd0-11e6-81f6-25b04f4e134a.png)

**Comment by brunopaisano** [comment]
@ariadnemelo Eu sinceramente não curti mto não rs! Vamos tentar fazer uma versão monocromática e passamos pra vc, pode ser?

**Comment by nicolavieira** [comment]
@brunopaisano ok, fica a critério de vocês

**Comment by brunopaisano** [comment]
Segue a imagem nova, @ariadnemelo ! Já fiz com o fundo branco atrás.
![barra_lateral_bichos_mono](https://cloud.githubusercontent.com/assets/20778816/17602431/f43f0006-5fe2-11e6-99a9-5e88baab41b6.png)

Tudo certo?
