### ISSUE TITLE
Criação e edição de fóruns

### ISSUE THREAD

**Issue by laurybueno** [hacklabr/paralapraca#483]
Grupos de fóruns também devem ser editáveis

**Comment by tiagofassoni** [comment]
- [x ] #484, #453 ~Se usuário for superuser, tem o poder de filtrar por contratos Senão, não.~
- [x]  Na tela de admin, aparece um filtro por contratos.

**Comment by tiagofassoni** [comment]
- [x] Telas de edição, listagem e criação de fórum no AVA, todas baseadas em forms de django

**Comment by tiagofassoni** [comment]
@virgilio Tá feito. Está nos branchs contracts do timtec, do django-discussion e do paralapraca.

Importante ressaltar que a remoção está diferente do que você pediu: aparece um formulário de remoção, ao invés de ser javascript. O motivo de eu ter feito assim era porque tinha uma view de django já para isso e era mais rápido (e a gente está aqui correndo na velocidade).

**Comment by leopiccionia** [comment]
@tiagofassoni Você sabe a diferença entre essa issue e a #452?
