### ISSUE TITLE
Corrigir layout da tela de mensagens

### ISSUE THREAD

**Issue by nicolavieira** [hacklabr/paralapraca#50]

**Comment by nicolavieira** [comment]
eu não consegui criar uma mensagem para testar, pode ver o que é @brunosmartin ?

**Comment by brunopaisano** [comment]
@brunosmartin é essa aqui que é pra fazer? Não sei exatamente do que se trata. Tem alguma referência pra seguir?

**Comment by laurybueno** [comment]
Issue superada por #329 e #332
