### ISSUE TITLE
Corrigir layout da tela de usuários

### ISSUE THREAD

**Issue by nicolavieira** [hacklabr/paralapraca#52]

**Comment by nicolavieira** [comment]
dei um tapa mas essa tela não tem layout @luisfbs  @brunopaisano

**Comment by brunopaisano** [comment]
@ariadnemelo , tela de usuários seria o perfil de algum usuário quando vc clica no nome dele num fórum, por exemplo? Se sim, é o mesmo layout da página de perfil do usuário logado 😃

**Comment by nicolavieira** [comment]
@brunopaisano não, é uma tela do admin, que você acessa pelo admin do curso... agora eu não to mais achando ela, mas pergunta pro @brunosmartin 

de qualquer jeito percebi agora que no ambiente de teste vocês não vão conseguir ver essas últimas alterações, o bruno precisa fazer um release lá

**Comment by brunopaisano** [comment]
Hmm acho que entendi rs! Vou falar com o @brunosmartin qualquer coisa.

**Comment by nicolavieira** [comment]
layout em
usuários - https://app.zeplin.io/project.html#pid=576ad22a40ea7eb4350a160f&sid=580a6196eb9f1db2525d3133
grupos - https://app.zeplin.io/project.html#pid=576ad22a40ea7eb4350a160f&sid=580a69068eebd11b0bebc80f
