### ISSUE TITLE
Criar um cheatsheet com todos os botões e links da plataforma e seus respectivos estados (hover/sem hover)

### ISSUE THREAD

**Issue by nicolavieira** [hacklabr/paralapraca#53]
Acho que ter isso num arquivo só facilitaria o meu trabalho e o de vocês, pois do jeito que está, com as explicações espalhadas em diversas telas fica difícil ver qual o padrão dos botões e links e o risco de algo passar batido é muito grande, o que acham? @luisfbs @brunopaisano

**Comment by brunopaisano** [comment]
Concordo, @ariadnemelo !

**Comment by brunopaisano** [comment]
Aqui está o link, @ariadnemelo ! Vou atualizando no Zeplin conforme for fazendo. 
https://zpl.io/f4sr5

**Comment by nicolavieira** [comment]
valeu @brunopaisano ! vai ajudar pra caramba, vou encerrar essa tarefa
