### ISSUE TITLE
Resolver o problema das lupas no Módulo Introdutório

### ISSUE THREAD

**Issue by helenalb** [hacklabr/paralapraca#60]
Elas ficam cortadas
![captura de tela de 2016-08-03 16-12-35](https://cloud.githubusercontent.com/assets/20777077/17378646/0a87d38c-5995-11e6-8ae5-2582c72f26a8.png)
@ariadnemelo

**Comment by nicolavieira** [comment]
foi resolvido ontem pelo @laurybueno
