### ISSUE TITLE
Fóruns - Visualizar todos os fóruns

### ISSUE THREAD

**Issue by marianamanfredi** [hacklabr/paralapraca#65]
Não é possível visualizar todo os fóruns do AVA

**Comment by brunopaisano** [comment]
@ariadnemelo Aqui está a issue de que estávamos falando. Vou fazer o botão!

**Comment by brunopaisano** [comment]
Pronto! Seguem os links para as telas com o novo botão no widget de fóruns:

Coordenadoras
Menu aberto: https://zpl.io/29OHup
Menu fechado: https://zpl.io/s3kmR

Assessoras:
Menu aberto: https://zpl.io/Z2nNox0
Menu fechado: https://zpl.io/Z16vD6q

OBS.: também dei uma mudada na posição da barra de busca no widget do fórum pq ele não tava bem alinhado. Faço uma issue nova pra isso?
