### ISSUE TITLE
Incluir bichos no painel lateral

### ISSUE THREAD

**Issue by marianamanfredi** [hacklabr/paralapraca#82]

**Comment by nicolavieira** [comment]
@luisfbs @brunopaisano preciso conversar com vocês para decidir como aplicar a imagem no menu lateral

**Comment by brunopaisano** [comment]
Bem melhor em monocromático! Valeu, @ariadnemelo !

**Comment by brunopaisano** [comment]
@ariadnemelo, o cliente deu um debrief dizendo que a barra tá muito poluída do jeito que está. dei uma suavizada no contraste entre os bichos e o fundo, segue uma nova imagem pra vc aplicar:

![barra_lateral_bichos_mono](https://cloud.githubusercontent.com/assets/20778816/17740152/f875e754-646d-11e6-8c81-8167bcd6e2de.png)
