### ISSUE TITLE
Ajustar padrão dos marcadores “x responderam” e “x gostaram” nas páginas e widget do fórum

### ISSUE THREAD

**Issue by nicolavieira** [hacklabr/paralapraca#91]
Nos marcadores "x responderam" e "x gostaram" o texto e o ícone devem ser coloridos se x > 0. Se x = 0 o texto deve permanecer cinza.

Por padrão o texto dos marcadores é cinza, para deixá-los coloridos é preciso criar uma regra que aplique a classe `active` quando x > 0.

Esse marcadores aparecem:
- no widget do fórum na dashboard
- na página inicial do fórum
- na página do tópico

**Comment by brunosmartin** [comment]
@ariadnemelo vc pode confirmar se está não está pronta, por favor? Ela está feita no tópico, mas não sei se nas outras tb... Vc termina ela? qq é só olhar como está na tela do tópico e generalizar pras outras.
