### ISSUE TITLE
Colocar data nos fóruns (posts, comentários, respostas, etc)

### ISSUE THREAD

**Issue by helenalb** [hacklabr/paralapraca#99]

**Comment by brunosmartin** [comment]
Aplicar o mesmo filtro das notificações paras as datas nos tópicos

**Comment by laurybueno** [comment]
@brunopaisano
As duas telas de fórum a seguir mostram a posição do texto de última edição do tópico em lugares diferentes. Qual é o lugar certo?
https://zpl.io/1l5bXW
https://zpl.io/1rzDgl

**Comment by brunopaisano** [comment]
Essa: http://zpl.io/1rzDgl

Inclusive acabar de atualizar a outra tela no Zeplin!

**Comment by laurybueno** [comment]
Na página de tópicos, o problema é resolvido pelo 732d8123710e51616b6aea528f57eb049e89b33b

**Comment by laurybueno** [comment]
Para o dashboard e a home de fóruns, a solução foi colocada no branch plpc-datas, já que não temos um layout aprovado para exibir datas recentes de modificação nessas páginas.

Abaixo, um print da solução que está agora no branch plpc-datas
![datas](https://cloud.githubusercontent.com/assets/1108897/18022427/3f78bd26-6bc5-11e6-9ac0-4a77a285a13b.png)

**Comment by laurybueno** [comment]
Para inserir datas de atividades recentes na tela do índice de fórum, eu tenho duas propostas.

Algumas das duas parece boa para vocês, @brunopaisano @luisfbs? Ou vocês preferem propor outro layout? 

![atividade-opcao-1](https://cloud.githubusercontent.com/assets/1108897/18054241/6c241530-6dd9-11e6-8422-d943c7a4f22a.png)
![atividade-opcao-2](https://cloud.githubusercontent.com/assets/1108897/18054242/6c259a04-6dd9-11e6-95ec-f997cf78702f.png)

**Comment by brunopaisano** [comment]
@laurybueno, eu prefiro a segunda opção, com a data de modificação recente em maior destaque, na primeira ela fica muito apagada. Acho que 3 informações (pessoa, tópico e fórum) na lógica de texto corrido já tá bom. Mais que isso pode até complicar em caso de muitos caracteres.

Uma coisa que eu reparei: nas telas do Zeplin, nós fizemos o número de respostas vindo antes do número de "gostei", e não depois, como está implementado. No widget está assim, e na tela de tópico está conforme o Zeplin. Precisamos padronizar isso.

Faço uma nova issue agora referente a isso? Caso prefiram tbm, eu espero pra colocar junto com outros problemas que já encontrei, aí faço tudo de uma vez.

**Comment by laurybueno** [comment]
ótimo, @brunopaisano, obrigado.

Sobre a segunda questão, acho melhor abrir outra issue. Mesmo porque não tenho certeza se entendi o problema.
